#! /bin/bash

__listings__() {

    __listing_pages() {
        local args="$*"
        local l_root="$current_dir"
        local l_pattern="*"
        local l_page_label="title"
        local -A l_globals_and=()
        local -A l_globals_or=()
        local str="$args"
        
        while [[ "$str" =~ ([a-zA-Z0-9_.-]+)=([^\"\'[:space:]]+|\"([^\"]+)\"|\'([^\']+)\') ]]; do
            local key="${BASH_REMATCH[1]}"
            local val="${BASH_REMATCH[4]:-${BASH_REMATCH[3]:-${BASH_REMATCH[2]}}}"
            if [[ "$key" == "root" ]]; then l_root="$val"
            elif [[ "$key" == "pattern" ]]; then l_pattern="$val"
            elif [[ "$key" == "page_label" ]]; then l_page_label="$val"
            elif [[ "$key" == globals.* ]]; then
                local g_key="${key#globals.}"
                if [[ "$val" == *" AND "* ]]; then
                    l_globals_and["$g_key"]="$val"
                else
                    l_globals_or["$g_key"]="$val"
                fi
            fi
            str="${str#*${BASH_REMATCH[0]}}"
        done
        
        [[ "$l_root" == "." || -z "$l_root" ]] && l_root=""
        
        local list_html="<list class=\"list-pages\">"$'\n'"<ul class=\"list-pages-ul\">"$'\n'
        
        local target_dir="$SOURCEDIR"
        if [[ -n "$l_root" ]]; then
            if [[ "$l_root" == /* ]]; then
                target_dir="$SOURCEDIR${l_root}"
            else
                target_dir="$SOURCEDIR/${l_root//./\/}"
            fi
        fi
        
        if [[ -d "$target_dir" ]]; then
            local f
            local force_globals=0
            [[ "$l_page_label" == globals.* ]] && force_globals=1
            
            for f in "$target_dir"/$l_pattern; do
                [[ -f "$f" ]] || continue
                local match=1
                local -A file_globals=()
                
                if [[ ${#l_globals_and[@]} -gt 0 || ${#l_globals_or[@]} -gt 0 || $force_globals -eq 1 ]]; then
                    local in_globals=0
                    while IFS= read -r g_line || [[ -n "$g_line" ]]; do
                        g_line="${g_line%$'\r'}"
                        if (( in_globals == 0 )); then
                            [[ "$g_line" =~ ^[[:space:]]*\{\{[[:space:]]*block\.globals[[:space:]]*\}\}[[:space:]]*$ ]] && in_globals=1
                        else
                            [[ "$g_line" =~ ^[[:space:]]*\{\{[[:space:]]*block\.end[[:space:]]*\}\}[[:space:]]*$ ]] && break
                            if [[ "$g_line" =~ ^[[:space:]]*::[[:space:]]*([a-zA-Z0-9_-]+):[[:space:]]*(.*)$ ]]; then
                                file_globals["${BASH_REMATCH[1]}"]="${BASH_REMATCH[2]}"
                            fi
                        fi
                    done < "$f"
                    
                    if [[ ${#l_globals_and[@]} -gt 0 || ${#l_globals_or[@]} -gt 0 ]]; then
                        local gk actual_v
                        for gk in "${!l_globals_and[@]}"; do
                            actual_v="${file_globals[$gk]:-}"
                            if [[ -z "$actual_v" ]]; then match=0; break; fi
                            local old_ifs="$IFS"; IFS=" AND "; local -a req_arr=(${l_globals_and[$gk]}); IFS="$old_ifs"
                            local req_v
                            for req_v in "${req_arr[@]}"; do
                                if [[ "$req_v" != "AND" && -n "${req_v// /}" ]]; then
                                    req_v="${req_v#"${req_v%%[![:space:]]*}"}"; req_v="${req_v%"${req_v##*[![:space:]]}"}"
                                    if [[ $actual_v != *$req_v* ]]; then match=0; break; fi
                                fi
                            done
                            (( match == 0 )) && break
                        done
                        if (( match == 1 )); then
                            for gk in "${!l_globals_or[@]}"; do
                                actual_v="${file_globals[$gk]:-}"
                                if [[ -z "$actual_v" ]]; then match=0; break; fi
                                local or_match=0
                                local old_ifs="$IFS"; IFS=" OR "; local -a req_arr=(${l_globals_or[$gk]}); IFS="$old_ifs"
                                local req_v
                                for req_v in "${req_arr[@]}"; do
                                    if [[ "$req_v" != "OR" && -n "${req_v// /}" ]]; then
                                        req_v="${req_v#"${req_v%%[![:space:]]*}"}"; req_v="${req_v%"${req_v##*[![:space:]]}"}"
                                        if [[ $actual_v == *$req_v* ]]; then or_match=1; break; fi
                                    fi
                                done
                                if (( or_match == 0 )); then match=0; break; fi
                            done
                        fi
                    fi
                fi
                if (( match == 1 )); then
                    local fname="${f##*/}"
                    local p_url="" slug_key=""
                    if [[ -n "$l_root" ]]; then
                        p_url="${l_root//./\/}/${fname%.*}.html"
                        slug_key="${l_root//\//.}.${fname%.*}"
                    else
                        p_url="${fname%.*}.html"
                        slug_key="${fname%.*}"
                    fi
                    [[ "$p_url" != /* ]] && p_url="/${p_url}"
                    p_url="${p_url//\/\//\/}"
                    slug_key="${slug_key#.}"
                    
                    local disp_name=""
                    if [[ "$l_page_label" == globals.* ]]; then
                        local g_key="${l_page_label#globals.}"
                        disp_name="${file_globals[$g_key]:-}"
                    elif [[ "$l_page_label" == "name" ]]; then
                        disp_name="${fname%.*}"
                    elif [[ "$l_page_label" == "weight" ]]; then
                        disp_name="${PAGE_WEIGHTS[$slug_key]:-9999999}"
                    fi
                    
                    [[ -z "$disp_name" ]] && disp_name="${PAGE_TITLES[$slug_key]:-${fname%.*}}"
                    
                    list_html+="<li class=\"list-pages-li\"><a href=\"$p_url\">$disp_name</a></li>"$'\n'
                fi
            done
        fi
        list_html+="</ul>"$'\n'"</list>"
        printf "%s" "$list_html"
    }

    __listing_blocks() {
        local b_type="$1"
        shift
        local singular="${b_type%s}"
        local l_root="" l_depth="999" l_page=""
        
        if [[ $# -eq 1 && "$1" != *=* ]]; then
            l_page="$1"
        else
            local str="$*"
            while [[ "$str" =~ ([a-zA-Z0-9_.-]+)=([^\"\'[:space:]]+|\"([^\"]+)\"|\'([^\']+)\') ]]; do
                local key="${BASH_REMATCH[1]}"
                local val="${BASH_REMATCH[4]:-${BASH_REMATCH[3]:-${BASH_REMATCH[2]}}}"
                if [[ "$key" == "root" ]]; then l_root="$val"
                elif [[ "$key" == "depth" ]]; then l_depth="$val"
                elif [[ "$key" == "page" ]]; then l_page="$val"
                fi
                str="${str#*${BASH_REMATCH[0]}}"
            done
        fi

        local list_html="<list class=\"list-block-${singular}\">"$'\n'"<ul class=\"list-block-${singular}-ul\">"$'\n'
        local -a target_files=()

        if [[ -n "$l_page" ]]; then
            local t_file="$SOURCEDIR/${l_page//./\/}"
            [[ "$t_file" != *.md ]] && t_file="${t_file}.md"
            if [[ -f "$t_file" ]]; then target_files+=("$t_file"); fi
        elif [[ -n "$l_root" ]]; then
            local t_dir="$SOURCEDIR/${l_root//./\/}"
            if [[ -d "$t_dir" ]]; then
                while IFS= read -r -d '' f; do
                    local rel="${f#$t_dir/}"
                    local d_count="${rel//[^\/]/}"
                    if (( ${#d_count} < l_depth )); then
                        target_files+=("$f")
                    fi
                done < <(find "$t_dir" -type f -name "*.md" -print0)
            fi
        else
            target_files+=("$file")
        fi

        local t_f
        for t_f in "${target_files[@]}"; do
            local t_rel="${t_f#$SOURCEDIR/}"
            local t_url="/${t_rel%.md}.html"
            local in_block="" block_id="" first_key="" first_val=""
            local b_context="" b_entity=""
            local item_count_table=0 item_count_diagram=0
            local -a t_buffer=()
            while IFS= read -r t_line || [[ -n "$t_line" ]]; do
                t_line="${t_line%$'\r'}"
                if [[ -z "$in_block" ]]; then
                    if [[ "$t_line" =~ ^[[:space:]]*\{\{[[:space:]]*block\.([a-zA-Z0-9_-]+)[[:space:]]*\}\}[[:space:]]*$ ]]; then
                        local match_type="${BASH_REMATCH[1]}"
                        if [[ "$match_type" == "table" ]]; then ((item_count_table++)); fi
                        if [[ "$match_type" == "diagram" ]]; then ((item_count_diagram++)); fi
                        
                        if [[ "$match_type" == "$b_type" || "$match_type" == "$singular" || "${match_type}s" == "$b_type" ]]; then
                            in_block="$match_type"
                            block_id="" first_key="" first_val=""
                            b_context="" b_entity=""
                            if [[ "$in_block" == "table" ]]; then t_buffer=(); fi
                        fi
                    fi
                else
                    if [[ "$t_line" =~ ^[[:space:]]*\{\{[[:space:]]*block\.end[[:space:]]*\}\}[[:space:]]*$ ]]; then
                        if [[ "$in_block" == "table" ]]; then
                            local caption="" sep_count=0 i
                            for ((i=0; i<${#t_buffer[@]}; i++)); do
                                if [[ "${t_buffer[$i]}" =~ ^[-=_]{4,} ]]; then ((sep_count++)); fi
                            done
                            if [[ $sep_count -ge 2 ]]; then
                                local found_sep=0
                                for ((i=0; i<${#t_buffer[@]}; i++)); do
                                    if [[ "${t_buffer[$i]}" =~ ^[-=_]{4,} ]]; then ((found_sep++)); continue; fi
                                    if [[ $found_sep -eq $sep_count ]]; then
                                        local cl="${t_buffer[$i]}"
                                        cl="${cl#"${cl%%[![:space:]]*}"}"; cl="${cl%"${cl##*[![:space:]]}"}"
                                        if [[ -n "$cl" ]]; then caption="$cl"; break; fi
                                    fi
                                done
                            fi
                            list_html+="<li class=\"list-block-${singular}-li\"><a href=\"${t_url}#table-${item_count_table}\">${caption:-Table ${item_count_table}}</a></li>"$'\n'
                        elif [[ "$in_block" == "diagram" ]]; then
                            list_html+="<li class=\"list-block-${singular}-li\"><a href=\"${t_url}#diagram-${item_count_diagram}\">Diagram ${item_count_diagram}</a></li>"$'\n'
                        else
                            local disp_val="${b_entity:-${b_context:+"${b_context} - "}${first_val}}"
                            local raw_id="${block_id:-${b_entity:-$first_val}}"
                            local clean_id="$(__slugify "$raw_id")"
                            local ref_key="$clean_id"
                            if [[ -n "$b_context" && "$raw_id" != *.* ]]; then
                                ref_key="$(__slugify "${b_context}.${raw_id}")"
                            fi
                            local anchor_id_slug="${ref_key//./-}"
                            local anchor_id="block-${in_block}-${anchor_id_slug}"
                            list_html+="<li class=\"list-block-${singular}-li\"><a href=\"${t_url}#${anchor_id}\">${disp_val:-$anchor_id}</a></li>"$'\n'
                        fi
                        in_block=""
                    else
                        if [[ "$in_block" == "table" ]]; then
                            t_buffer+=("$t_line")
                        elif [[ "$t_line" =~ ^[[:space:]]*::[[:space:]]*([a-zA-Z0-9_-]+):[[:space:]]*(.*)$ ]]; then
                            local k="${BASH_REMATCH[1]}" v="${BASH_REMATCH[2]}"
                            v="${v#"${v%%[![:space:]]*}"}"; v="${v%"${v##*[![:space:]]}"}"
                            if [[ "$k" == "__id__" ]]; then block_id="$v"; fi
                            if [[ "$k" == "__context__" || "$k" == "context" ]]; then b_context="$v"; fi
                            if [[ "$k" == "__entity__" || "$k" == "__entry__" ]]; then b_entity="$v"; fi
                            if [[ -z "$first_key" && "$k" != "__id__" && "$k" != "__context__" && "$k" != "context" && "$k" != "__entry__" && "$k" != "__entity__" ]]; then
                                first_key="$k"; first_val="$v"
                            fi
                        fi
                    fi
                fi
            done < "$t_f"
        done

        list_html+="</ul>"$'\n'"</list>"
        printf "%s" "$list_html"
    }
    
}
