#! /bin/bash

__parse__() {
    __parse_item() {
        local indent="$1" ltype="$2" item_content="$3" line_prefix=""
        while (( list_depth > 0 )) && (( indent < LIST_INDENTS[list_depth-1] )); do
            list_depth=$((list_depth - 1))
            line_prefix+="</li></${LIST_TYPES[list_depth]}>"
        done
        if (( list_depth == 0 )) || (( indent > LIST_INDENTS[list_depth-1] )); then
            LIST_INDENTS[$list_depth]="$indent"
            LIST_TYPES[$list_depth]="$ltype"
            list_depth=$((list_depth + 1))
            line_prefix+="<${ltype}><li>"
        elif (( indent == LIST_INDENTS[list_depth-1] )); then
            if [[ "${LIST_TYPES[list_depth-1]}" != "$ltype" ]]; then
                line_prefix+="</li></${LIST_TYPES[list_depth-1]}><${ltype}><li>"
                LIST_TYPES[$list_depth-1]="$ltype"
            else
                line_prefix+="</li><li>"
            fi
        else
            if [[ "${LIST_TYPES[list_depth-1]}" != "$ltype" ]]; then
                line_prefix+="</li></${LIST_TYPES[list_depth-1]}><${ltype}><li>"
                LIST_TYPES[$list_depth-1]="$ltype"
            else
                line_prefix+="</li><li>"
            fi
        fi
        line="${line_prefix}${item_content}"
    }
    
    __parse_ul() { __parse_item "$1" "ul" "$2"; }
    __parse_ol() { __parse_item "$1" "ol" "$2"; }
    
    __parse_list() {
        if (( list_depth > 0 )); then
            while (( list_depth > 0 )); do
                list_depth=$((list_depth - 1))
                content+="</li></${LIST_TYPES[list_depth]}>"$'\n'
            done
            LIST_INDENTS=()
            LIST_TYPES=()
        fi
    }

    __parse_inline() {
        if [[ "$line" == *"\`"* ]]; then
            local code_re='`([^`]+)`'
            while [[ "$line" =~ $code_re ]]; do
                local full="${BASH_REMATCH[0]}" code="${BASH_REMATCH[1]}"
                code="${code//&/$_amp}"; code="${code//</$_lt}"; code="${code//>/$_gt}"
                local old_line="$line"
                masked_codes[$m_idx]="<inline>${code}</inline>"
                line="${line/"$full"/%%MASKED_${m_idx}%%}"
                ((m_idx++))
                if [[ "$line" == "$old_line" ]]; then break; fi
            done
        fi
    }

    __parse_pre() {
        if [[ "$line" == *"<pre"* && "$line" == *"</pre>"* ]]; then
            local temp_line="$line"
            while [[ "$temp_line" == *"<pre"* && "$temp_line" == *"</pre>"* ]]; do
                local before_pre="${temp_line%%<pre*}"
                local rest="${temp_line#*$before_pre}"
                local full_pre="${rest%%</pre>*}</pre>"
                local old_line="$temp_line"
                
                local open_tag="${full_pre%%>*}"
                local inner_content="${full_pre#*>}"
                inner_content="${inner_content%</pre>*}"
                
                inner_content="${inner_content//&/$_amp}"
                inner_content="${inner_content//</$_lt}"
                inner_content="${inner_content//>/$_gt}"
                
                masked_codes[$m_idx]="${open_tag}>${inner_content}</pre>"
                temp_line="${temp_line/"$full_pre"/%%MASKED_${m_idx}%%}"
                ((m_idx++))
                if [[ "$temp_line" == "$old_line" ]]; then break; fi
            done
            line="$temp_line"
        fi
    }

    __parse_strong() {
        if [[ "$line" == *"**"* || "$line" == *"__"* ]]; then
            while [[ "$line" == *"**"*"**"* ]]; do
                local old_line="$line"
                line="${line/\*\*/<strong>}"; line="${line/\*\*/<\/strong>}"
                if [[ "$line" == "$old_line" ]]; then break; fi
            done
            while [[ "$line" == *"__"*"__"* ]]; do
                local old_line="$line"
                line="${line/__/<strong>}"; line="${line/__/<\/strong>}"
                if [[ "$line" == "$old_line" ]]; then break; fi
            done
        fi
    }

    __parse_underline() {
        if [[ "$line" == *"++"* ]]; then
            while [[ "$line" == *"++"*"++"* ]]; do
                local old_line="$line"
                line="${line/\+\+/<ins>}"
                line="${line/\+\+/<\/ins>}"
                if [[ "$line" == "$old_line" ]]; then break; fi
            done
        fi
    }

    __parse_em() {
        if [[ "$line" == *"_"*"_"* ]]; then
            local em_re='(^|[[:space:][:punct:]])_([a-zA-Z0-9][^_]+)_([[:space:][:punct:]]|$)'
            while [[ "$line" =~ $em_re ]]; do
                local full="${BASH_REMATCH[0]}" pre="${BASH_REMATCH[1]}" t_content="${BASH_REMATCH[2]}" post="${BASH_REMATCH[3]}"
                if [[ "$t_content" == *"/"* || "$t_content" == *"="* ]]; then break; fi
                local old_line="$line"
                line="${line/"$full"/${pre}<em>${t_content}</em>${post}}"
                if [[ "$line" == "$old_line" ]]; then break; fi
            done
        fi
    }
 
    __parse_refs() {
        if [[ "$line" == *"{{"*":"*"}}"* ]]; then
            local topic_re='\{\{[[:space:]]*([a-zA-Z0-9_-]+):([^:}]+)(:([^}]+))?[[:space:]]*\}\}'
            while [[ "$line" =~ $topic_re ]]; do
                local full="${BASH_REMATCH[0]}"
                local topic="${BASH_REMATCH[1]}"
                local raw_ref="${BASH_REMATCH[2]}"
                local label="${BASH_REMATCH[4]}"
                raw_ref="${raw_ref#"${raw_ref%%[![:space:]]*}"}"
                raw_ref="${raw_ref%"${raw_ref##*[![:space:]]}"}"
                if [[ -z "$label" ]]; then
                    label="$raw_ref"
                else
                    label="${label#"${label%%[![:space:]]*}"}"
                    label="${label%"${label##*[![:space:]]}"}"
                fi
                local ref_key=""
                if type __slugify >/dev/null 2>&1; then
                    ref_key="$(__slugify "$raw_ref")"
                else
                    ref_key="${raw_ref//[^a-zA-Z0-9_.-]/}"
                fi
                local old_line="$line"
                line="${line/"$full"/%%WIKI_REF:${topic}:${ref_key}:${label}%%}"
                if [[ "$line" == "$old_line" ]]; then break; fi
            done
        fi
        if [[ "$line" == *"{{#"* || "$line" == *"{{="* ]]; then
            local mark_re='\{\{\#([a-zA-Z0-9_.-]+)\}\}'
            local anchor_re='\{\{\=([a-zA-Z0-9_.-]+)\}\}'
            while [[ "$line" =~ $mark_re ]]; do
                local full="${BASH_REMATCH[0]}"
                local old_line="$line"
                line="${line/"$full"/<span id=\"${BASH_REMATCH[1]}\" class=\"wiki-mark\"></span>}"
                if [[ "$line" == "$old_line" ]]; then break; fi
            done
            while [[ "$line" =~ $anchor_re ]]; do
                local full="${BASH_REMATCH[0]}"
                local old_line="$line"
                line="${line/"$full"/<a href=\"#${BASH_REMATCH[1]}\">${BASH_REMATCH[1]}</a>}"
                if [[ "$line" == "$old_line" ]]; then break; fi
            done
        fi
    } 

    __parse_links() {
        if [[ "$line" == *"["* && "$line" == *"]("* ]]; then
            local link_re='\[([^]]+)\]\(([^)]+)\)'
            while [[ "$line" =~ $link_re ]]; do
                local full="${BASH_REMATCH[0]}" l_text="${BASH_REMATCH[1]}" l_href="${BASH_REMATCH[2]}"
                if [[ "$l_href" != http://* && "$l_href" != https://* ]]; then
                    if [[ "$l_href" =~ ^(.*)\.(md|markdown|MD|MARKDOWN)([ \t#].*)?$ ]]; then
                        l_href="${BASH_REMATCH[1]}.html${BASH_REMATCH[3]}"
                    fi
                fi
                local old_line="$line"
                line="${line/"$full"/<a href=\"${l_href}\">${l_text}</a>}"
                if [[ "$line" == "$old_line" ]]; then break; fi
            done
        fi
    }


    __parse_tag() {
        if [[ "$line" == *"=="* ]]; then
            while [[ "$line" =~ (^|[^=])=([a-zA-Z0-9_-]+)=(.*) ]]; do
                local pre="${BASH_REMATCH[1]}"
                local tag="${BASH_REMATCH[2]}"
                local remainder="${BASH_REMATCH[3]}"
                if [[ "$remainder" != *"=="* ]]; then break; fi
                local content="${remainder%%==*}"
                local full="${pre}=${tag}=${content}=="
                local old_line="$line"
                line="${line/"$full"/${pre}<${tag}>${content}</${tag}>}"
                if [[ "$line" == "$old_line" ]]; then break; fi
            done
            while [[ "$line" == *"=="*"=="* ]]; do
                local old_line="$line"
                line="${line/==/<tag>}"; line="${line/==/<\/tag>}"
                if [[ "$line" == "$old_line" ]]; then break; fi
            done
        fi
    }

    __parse_markdown() {
        if [[ "$line" != *"\`"* && "$line" != *"*"* && "$line" != *"_"* && "$line" != *"+"* && "$line" != *"{"* && "$line" != *"["* && "$line" != *"<"* && "$line" != *"=="* ]]; then return; fi
        local -a masked_codes=()
        local m_idx=0
        __parse_pre
        __parse_inline
        __parse_strong
        __parse_underline
        __parse_em
        __parse_tag
        __parse_refs
        __parse_links
        for (( i=0; i<m_idx; i++ )); do
            line="${line//%%MASKED_${i}%%/${masked_codes[$i]}}"
        done
    }


    __parse_block_field() {
        local _field_ref="$1"
        if [[ -z "$_field_ref" ]]; then return; fi
        _field_ref="${_field_ref//$'\t'/    }"
        _field_ref="${_field_ref//$'\xC2\xA0'/ }"
        local tmp
        while [[ "$_field_ref" != "$tmp" ]]; do
            tmp="$_field_ref"
            _field_ref="${_field_ref#$'\n'}"
            _field_ref="${_field_ref#$'\r'}"
            _field_ref="${_field_ref%$'\n'}"
            _field_ref="${_field_ref%$'\r'}"
            _field_ref="${_field_ref% }"
        done
        local base_indent=-1
        local check_line
        while IFS= read -r check_line; do
            if [[ -n "${check_line//[[:space:]]/}" ]]; then
                [[ "$check_line" =~ ^([[:space:]]*) ]]
                local ind="${#BASH_REMATCH[1]}"
                if (( base_indent == -1 || ind < base_indent )); then
                    base_indent=$ind
                fi
            fi
        done <<< "$_field_ref"
        if (( base_indent > 0 )); then
            local stripped=""
            local l
            while IFS= read -r l || [[ -n "$l" ]]; do
                if [[ -n "${l//[[:space:]]/}" ]]; then
                    stripped+="${l:base_indent}"$'\n'
                else
                    stripped+="$l"$'\n'
                fi
            done <<< "$_field_ref"
            _field_ref="${stripped%$'\n'}"
        fi
        local out=""
        local in_inner=0 in_html_pre=0 list_depth=0 code_lang=""
        local prefix rest inner suffix
        local -a LIST_INDENTS=() LIST_TYPES=()
        while IFS= read -r l || [[ -n "$l" ]]; do
            if (( in_inner == 0 )); then
                if [[ "$l" =~ ^[[:space:]]*\`\`\`([a-zA-Z0-9_+-]*)[[:space:]]*$ ]]; then
                    if (( list_depth > 0 )); then
                        while (( list_depth > 0 )); do
                            list_depth=$((list_depth - 1))
                            out+="</li></${LIST_TYPES[list_depth]}>"
                        done
                        LIST_INDENTS=()
                        LIST_TYPES=()
                    fi
                    in_inner=1
                    code_lang="${BASH_REMATCH[1]}"
                    out+="${out:+$'\n'}<pre><code class=\"language-${code_lang}\">"$'\n'
                elif (( in_html_pre == 1 )); then
                    if [[ "$l" == *"</pre>"* ]]; then in_html_pre=0; fi
                    out+="${out:+$'\n'}$l"
                elif [[ "$l" == *"<pre"* && "$l" != *"</pre>"* ]]; then
                    in_html_pre=1
                    out+="${out:+$'\n'}$l"
                else
                    local is_list=0 indent="" marker=""
                    if [[ "$l" =~ ^([[:space:]]*)([-*+]|[0-9]+\.)[[:space:]]+(.*)$ ]]; then
                        is_list=1
                        indent="${#BASH_REMATCH[1]}"
                        marker="${BASH_REMATCH[2]}"
                        l="${BASH_REMATCH[3]}"
                    else
                        if (( list_depth > 0 )); then
                            if [[ -z "${l//[[:space:]]/}" ]]; then
                                continue
                            fi
                            if [[ ! "$l" =~ ^[[:space:]]+ ]]; then
                                while (( list_depth > 0 )); do
                                    list_depth=$((list_depth - 1))
                                    out+="</li></${LIST_TYPES[list_depth]}>"
                                done
                                LIST_INDENTS=()
                                LIST_TYPES=()
                            fi
                        fi
                    fi
                    while [[ "$l" == *\*\**\*\** ]]; do
                        prefix="${l%%\*\**}"; rest="${l#*\*\*}"
                        inner="${rest%%\*\**}"; suffix="${rest#*\*\*}"
                        l="${prefix}<strong>${inner}</strong>${suffix}"
                    done
                    while [[ "$l" == *_*_* ]]; do
                        prefix="${l%%_*}"; rest="${l#*_}"
                        inner="${rest%%_*}"; suffix="${rest#*_}"
                        l="${prefix}<em>${inner}</em>${suffix}"
                    done
                    while [[ "$l" == *\`*\`* ]]; do
                        prefix="${l%%\`*}"; rest="${l#*\`}"
                        inner="${rest%%\`*}"; suffix="${rest#*\`}"
                        l="${prefix}<inline>${inner}</inline>${suffix}"
                    done
                    while [[ "$l" == *"++"*"++"* ]]; do
                        local old_l="$l"
                        l="${l/\+\+/<ins>}"
                        l="${l/\+\+/<\/ins>}"
                        if [[ "$l" == "$old_l" ]]; then break; fi
                    done
                    if [[ "$l" == *"=="* ]]; then
                        while [[ "$l" =~ (^|[^=])=([a-zA-Z0-9_-]+)=(.*) ]]; do
                            local pre="${BASH_REMATCH[1]}"
                            local tag="${BASH_REMATCH[2]}"
                            local remainder="${BASH_REMATCH[3]}"
                            if [[ "$remainder" != *"=="* ]]; then break; fi
                            local content="${remainder%%==*}"
                            local full="${pre}=${tag}=${content}=="
                            local old_l="$l"
                            l="${l/"$full"/${pre}<${tag}>${content}</${tag}>}"
                            if [[ "$l" == "$old_l" ]]; then break; fi
                        done
                        while [[ "$l" == *"=="*"=="* ]]; do
                            local old_l="$l"
                            l="${l/==/<tag>}"; l="${l/==/<\/tag>}"
                            if [[ "$l" == "$old_l" ]]; then break; fi
                        done
                    fi
                    if [[ "$l" == *"["* && "$l" == *"]("* ]]; then
                        local link_re='\[([^]]+)\]\(([^)]+)\)'
                        while [[ "$l" =~ $link_re ]]; do
                            local full="${BASH_REMATCH[0]}" l_text="${BASH_REMATCH[1]}" l_href="${BASH_REMATCH[2]}"
                            if [[ "$l_href" != http://* && "$l_href" != https://* ]]; then
                                if [[ "$l_href" =~ ^(.*)\.(md|markdown|MD|MARKDOWN)([ \t#].*)?$ ]]; then
                                    l_href="${BASH_REMATCH[1]}.html${BASH_REMATCH[3]}"
                                fi
                            fi
                            l="${l/"$full"/<a href=\"${l_href}\">${l_text}</a>}"
                        done
                    fi
                    
                    local temp_line="$line"
                    line="$l"
                    __parse_refs
                    l="$line"
                    line="$temp_line"

                    if (( is_list == 1 )); then
                        local ltype="ul"
                        [[ "$marker" =~ ^[0-9] ]] && ltype="ol"
                        if (( list_depth == 0 )) || (( indent > LIST_INDENTS[list_depth-1] )); then
                            LIST_INDENTS[$list_depth]="$indent"
                            LIST_TYPES[$list_depth]="$ltype"
                            list_depth=$((list_depth + 1))
                            out+="<${ltype}><li>${l}"
                        else
                            while (( list_depth > 0 && indent < LIST_INDENTS[list_depth-1] )); do
                                list_depth=$((list_depth - 1))
                                out+="</li></${LIST_TYPES[list_depth]}>"
                            done
                            if (( list_depth == 0 )); then
                                LIST_INDENTS[$list_depth]="$indent"
                                LIST_TYPES[$list_depth]="$ltype"
                                list_depth=$((list_depth + 1))
                                out+="<${ltype}><li>${l}"
                            elif [[ "${LIST_TYPES[list_depth-1]}" != "$ltype" ]]; then
                                out+="</li></${LIST_TYPES[list_depth-1]}><${ltype}><li>${l}"
                                LIST_TYPES[$list_depth-1]="$ltype"
                            else
                                out+="</li><li>${l}"
                            fi
                        fi
                    else
                        out+="${out:+$'\n'}$l"
                    fi
                fi
            else
                if [[ "${l//[[:space:]]/}" == "\`\`\`" ]]; then
                    in_inner=0
                    out+="</code></pre>"
                else
                    l="${l//&/$_amp}"; l="${l//</$_lt}"; l="${l//>/$_gt}"
                    out+="$l"$'\n'
                fi
            fi
        done <<< "$_field_ref"
        if (( list_depth > 0 )); then
            while (( list_depth > 0 )); do
                list_depth=$((list_depth - 1))
                out+="</li></${LIST_TYPES[list_depth]}>"
            done
            LIST_INDENTS=()
            LIST_TYPES=()
        fi
        printf "%s" "$out"
    }


    __parse_code() {
        if (( in_code_block == 1 )); then
            local l_trim="${line#"${line%%[![:space:]]*}"}"
            l_trim="${l_trim%"${l_trim##*[![:space:]]}"}"

            if [[ "$l_trim" == "{{"*"block.end"*"}}" ]]; then
                content+="</code></pre>"$'\n'
                in_code_block=0
                ignore_next_empty=1
            else
                local safe_line="${line//&/$_amp}"
                safe_line="${safe_line//</$_lt}"
                safe_line="${safe_line//>/$_gt}"
                content+="${safe_line}"$'\n'
            fi
            return 0
        fi
        if [[ -z "$in_custom_block" ]]; then
            local l_trim="${line#"${line%%[![:space:]]*}"}"
            l_trim="${l_trim%"${l_trim##*[![:space:]]}"}"

            if [[ "$l_trim" == "{{"*"block.code"*"}}" ]]; then
                (( list_depth > 0 )) && __parse_list
                content="${content%<br><br>$'\n'}"
                in_code_block=1

                local args="${l_trim#*block.code}"
                args="${args%"}}"}"

                local lang=""
                if [[ "$args" == *"lang="* ]]; then
                    local tmp="${args##*lang=}"
                    lang="${tmp%%[!a-zA-Z0-9_+-#]*}"
                fi

                local classes="hljs"
                local has_lang=0
                if [[ -n "$lang" && "$lang" != "plaintext" && "$lang" != "none" ]]; then
                    classes+=" language-${lang}"
                    has_lang=1
                else
                    classes+=" nohighlight"
                fi

                if [[ "$args" == *"numbered=true"* ]]; then
                    classes+=" line-numbers"
                fi

                if [[ $has_lang -eq 1 ]]; then
                    content+="<pre><code class=\"${classes}\">"$'\n'
                else
                    content+="<pre><code class=\"${classes}\">"
                fi
                return 0
            fi
        fi
        return 1
    }   

    __parse_html() {
        if [[ -n "$in_custom_block" ]]; then return 1; fi
        if (( in_html_pre == 1 )); then
            if [[ "$line" == *"</pre>"* ]]; then
                in_html_pre=0
                local before_close="${line%%</pre>*}"
                local after_close="${line#*</pre>}"
                
                before_close="${before_close//&/$_amp}"
                before_close="${before_close//</$_lt}"
                before_close="${before_close//>/$_gt}"
                
                content+="${before_close}</pre>${after_close}"$'\n'
            else
                local safe_line="$line"
                safe_line="${safe_line//&/$_amp}"
                safe_line="${safe_line//</$_lt}"
                safe_line="${safe_line//>/$_gt}"
                
                content+="${safe_line}"$'\n'
            fi
            return 0
        fi
        if [[ "$line" == *"<pre"* && "$line" != *"</pre>"* ]]; then
            in_html_pre=1
            local open_tag="${line%%>*}"
            local after_open="${line#*>}"
            
            after_open="${after_open//&/$_amp}"
            after_open="${after_open//</$_lt}"
            after_open="${after_open//>/$_gt}"
            
            content+="${open_tag}>${after_open}"$'\n'
            return 0
        fi
        return 1
    }

    __parse_blocks() {
        if [[ -n "$in_custom_block" ]]; then
            if [[ "$line" =~ ^([[:space:]]*)\{\{[[:space:]]*block\.end[[:space:]]*\}\}[[:space:]]*$ ]] && [[ "${BASH_REMATCH[1]}" == "$custom_block_indent" ]]; then
                if [[ "$in_custom_block" == "table" ]]; then __block_table
                elif [[ "$in_custom_block" == "diagram" ]]; then __block_diagram
                elif [[ "$in_custom_block" == "hide" ]]; then __block_hide
                elif [[ "$in_custom_block" == "row" ]]; then __block_row "row" custom_block_buffer
                elif [[ "$in_custom_block" == "carousel" ]]; then __block_carousel "carousel" custom_block_buffer
                elif [[ "$in_custom_block" == "card" ]]; then __block_card "card" custom_block_buffer
                elif [[ "$in_custom_block" == "buttons" ]]; then __block_buttons "buttons" custom_block_buffer
                elif [[ "$in_custom_block" == "text" ]]; then __block_text "text" custom_block_buffer
                elif [[ "$in_custom_block" == "image" ]]; then __block_image "image" custom_block_buffer
                elif [[ "$in_custom_block" == "grid" ]]; then __block_grid "grid" custom_block_buffer
                elif [[ "$in_custom_block" == "plain" ]]; then __block_plain "plain" custom_block_buffer
                elif [[ "$in_custom_block" == "quote" ]]; then __block_quote "quote" custom_block_buffer
                elif [[ "$in_custom_block" == "globals" || "$in_custom_block" == "comment" ]]; then :
                elif [[ -n "${WIKI_BLOCKS[$in_custom_block]:-}" ]]; then content+="</div>"$'\n'
                elif [[ "$in_custom_block" == "blockquote" ]]; then content+="</blockquote>"$'\n'
                else
                    if declare -F "__block_${in_custom_block}" >/dev/null; then
                        "__block_${in_custom_block}" "$in_custom_block" custom_block_buffer
                    else
                        __block_core "$in_custom_block" custom_block_buffer
                    fi
                fi
                in_custom_block=""; custom_block_indent=""; ignore_next_empty=1; return 0
            else
                if [[ "$in_custom_block" == "table" ]]; then table_buffer+=("$line"); return 0; fi
                if [[ "$in_custom_block" == "diagram" ]]; then diagram_buffer+=("$line"); return 0; fi
                if [[ "$in_custom_block" == "hide" ]]; then hide_buffer+=("$line"); return 0; fi
                if [[ "$in_custom_block" == "globals" || "$in_custom_block" == "comment" ]]; then
                    if [[ "$in_custom_block" == "globals" && "$line" =~ ^[[:space:]]*::[[:space:]]*([a-zA-Z0-9_-]+):[[:space:]]*(.*)$ ]]; then
                        local gk="${BASH_REMATCH[1]}"
                        local gv="${BASH_REMATCH[2]}"
                        gv="${gv#"${gv%%[![:space:]]*}"}"
                        gv="${gv%"${gv##*[![:space:]]}"}"
                        PAGE_VARS["page.$gk"]="$gv"
                    fi
                    return 0
                fi
                if [[ -n "${WIKI_BLOCKS[$in_custom_block]:-}" ]]; then content+="$line"$'\n'; return 0; fi
                custom_block_buffer+=("$line"); return 0
            fi
        else
            if [[ "$line" =~ ^([[:space:]]*)\{\{[[:space:]]*block\.([a-zA-Z0-9_-]+)[[:space:]]*\}\}[[:space:]]*$ ]]; then
                content="${content%<br><br>$'\n'}"
                local curr_indent="${BASH_REMATCH[1]}"
                local bname="${BASH_REMATCH[2]}"
                if [[ "$bname" == "table" ]]; then
                    in_custom_block="table"; custom_block_indent="$curr_indent"; table_buffer=(); return 0
                elif [[ "$bname" == "diagram" ]]; then
                    in_custom_block="diagram"; custom_block_indent="$curr_indent"; diagram_buffer=(); return 0
                elif [[ "$bname" == "hide" ]]; then
                    in_custom_block="hide"; custom_block_indent="$curr_indent"; hide_buffer=(); return 0
                elif [[ "$bname" == "row" || "$bname" == "carousel" || "$bname" == "card" || "$bname" == "buttons" || "$bname" == "text" || "$bname" == "image" || "$bname" == "grid" || "$bname" == "quote" ]]; then
                    in_custom_block="$bname"; custom_block_indent="$curr_indent"; custom_block_buffer=(); return 0
                elif [[ "$bname" == "globals" || "$bname" == "comment" ]]; then
                    in_custom_block="$bname"; custom_block_indent="$curr_indent"; return 0
                elif [[ -n "${WIKI_BLOCKS[$bname]:-}" ]]; then
                    in_custom_block="$bname"; custom_block_indent="$curr_indent"
                    content+="<div class=\"${WIKI_BLOCKS[$bname]}\">"$'\n'
                    return 0
                else
                    in_custom_block="$bname"; custom_block_indent="$curr_indent"; custom_block_buffer=(); return 0
                fi
            fi
        fi
        return 1
    }

    __parse_vars() {
        if [[ "$line" == *"{{"* ]]; then
            if [[ "$line" =~ ^\s*\{\{\ *toc\ *\}\}\s*$ ]]; then line="{{TOC_PLACEHOLDER}}"; set_ignore_this_turn=1; fi
        fi
    }

    __parse_headers() {
        if [[ "$line" == "#"* ]]; then
            if [[ "$line" =~ ^(#{1,6})(\{([^}]+)\})?[[:space:]]+(.*)$ ]]; then
                (( list_depth > 0 )) && __parse_list
                local h_level="${#BASH_REMATCH[1]}"
                local attr_block="${BASH_REMATCH[3]}"
                local h_text="${BASH_REMATCH[4]}"
                local style_str=""
                
                if [[ -n "$attr_block" ]]; then
                    local IFS_old="$IFS"
                    IFS=','
                    local attrs=($attr_block)
                    IFS="$IFS_old"
                    local attr k v
                    for attr in "${attrs[@]}"; do
                        attr="${attr#"${attr%%[![:space:]]*}"}"
                        attr="${attr%"${attr##*[![:space:]]}"}"
                        k="${attr%%=*}"
                        v="${attr#*=}"
                        [[ "$k" == "align" ]] && k="text-align"
                        style_str+="${k}: ${v}; "
                    done
                    [[ -n "$style_str" ]] && style_str=" style=\"${style_str% }\""
                fi
                
                local slug="${h_text,,}"
                slug="${slug// /_}"; slug="${slug//[^a-z0-9_-]/}"
                line="<h${h_level} id=\"${slug}\"${style_str}>${h_text}</h${h_level}>"
                TOC_HTML+="<li class=\"toc-h${h_level}\"><a href=\"#${slug}\">${h_text}</a></li>"$'\n'
                set_ignore_this_turn=1
                
            elif [[ "$line" =~ ^#\!(\{([^}]+)\})?[[:space:]]+(.*)$ ]]; then
                local attr_block="${BASH_REMATCH[2]}"
                local h_text="${BASH_REMATCH[3]}"
                local style_str=""
                
                if [[ -n "$attr_block" ]]; then
                    local IFS_old="$IFS"
                    IFS=','
                    local attrs=($attr_block)
                    IFS="$IFS_old"
                    local attr k v
                    for attr in "${attrs[@]}"; do
                        attr="${attr#"${attr%%[![:space:]]*}"}"
                        attr="${attr%"${attr##*[![:space:]]}"}"
                        k="${attr%%=*}"
                        v="${attr#*=}"
                        [[ "$k" == "align" ]] && k="text-align"
                        style_str+="${k}: ${v}; "
                    done
                    [[ -n "$style_str" ]] && style_str=" style=\"${style_str% }\""
                fi
                
                line="<h0${style_str}>${h_text}</h0>"
                set_ignore_this_turn=1
            fi
        fi
    }  

    __parse_markers() {
        if [[ "$line" =~ ^([[:space:]]*)([-*+]|[0-9]+\.)[[:space:]]+(.*)$ ]]; then
            local indent="${#BASH_REMATCH[1]}" marker="${BASH_REMATCH[2]}" item_content="${BASH_REMATCH[3]}"
            if [[ "$marker" =~ ^[0-9] ]]; then __parse_ol "$indent" "$item_content"; else __parse_ul "$indent" "$item_content"; fi
            return 1
        else
            if (( list_depth > 0 )); then
                if [[ -z "${line//[[:space:]]/}" ]]; then
                    if [[ $ignore_next_empty -eq 1 ]]; then return 0; fi
                    if [[ $was_empty -eq 0 ]]; then content+="<br><br>"$'\n'; was_empty=1; fi
                    return 0
                fi
                if [[ ! "$line" =~ ^[[:space:]]+ ]]; then __parse_list; fi
            fi
        fi
        return 1
    }

    __parse_section() {
        if [[ "$line" =~ ^(@+)(\{([^}]+)\})?[[:space:]]*(.*)$ ]]; then
            (( list_depth > 0 )) && __parse_list
            local s_level="${#BASH_REMATCH[1]}"
            local attr_block="${BASH_REMATCH[3]}"
            local style_str=""
            
            if [[ -n "$attr_block" ]]; then
                local IFS_old="$IFS"
                IFS=','
                local attrs=($attr_block)
                IFS="$IFS_old"
                local attr k v
                for attr in "${attrs[@]}"; do
                    attr="${attr#"${attr%%[![:space:]]*}"}"
                    attr="${attr%"${attr##*[![:space:]]}"}"
                    k="${attr%%=*}"
                    v="${attr#*=}"
                    
                    if [[ "$k" == "align" ]]; then
                        local flex_align="$v"
                        [[ "$v" == "left" ]] && flex_align="flex-start"
                        [[ "$v" == "right" ]] && flex_align="flex-end"
                        style_str+="display: flex; justify-content: center; flex-direction: column; align-items: ${flex_align}; text-align: ${v}; "
                        continue
                    fi
                    
                    [[ "$k" == "bg" ]] && k="background-color"
                    style_str+="${k}: ${v}; "
                done
                [[ -n "$style_str" ]] && style_str=" style=\"${style_str% }\""
            fi
            
            ((section_count++))
            local sec_tag=""
            
            while (( ${#section_stack[@]} > 0 )); do
                local last_idx=$((${#section_stack[@]}-1))
                local last_val="${section_stack[$last_idx]}"
                if (( last_val >= s_level )); then
                    sec_tag+="</section>"$'\n'
                    unset "section_stack[$last_idx]"
                else
                    break
                fi
            done
            
            section_stack+=("$s_level")
            line="${sec_tag}<section class=\"section-${section_count} section-level-${s_level}\"${style_str}>"
            set_ignore_this_turn=1
        fi
    }


    __parse_main() {
        local section_count=0
        local -a section_stack=()
        for line in "${lines[@]}"; do
            set_ignore_this_turn=0
            line="${line%$'\r'}"
            __parse_code && continue
            __parse_blocks && continue
            __parse_html && continue
            
            __parse_vars
            __parse_headers
            __parse_section
            __parse_markers && continue
            __parse_markdown
            
            if [[ -z "${line//[[:space:]]/}" ]]; then
                if [[ $ignore_next_empty -eq 1 ]]; then :
                elif [[ $was_empty -eq 0 ]]; then content+="<br><br>"$'\n'; was_empty=1; fi
            else
                content+="${line}"$'\n'; was_empty=0
                if [[ $set_ignore_this_turn -eq 1 ]]; then ignore_next_empty=1; else ignore_next_empty=0; fi
            fi
        done
        __parse_list
        while (( ${#section_stack[@]} > 0 )); do
            content+="</section>"$'\n'
            unset "section_stack[$((${#section_stack[@]}-1))]"
        done
    }    
}
