#! /bin/bash

__partials__() {
   
    __partial_featured() {
        local -a _featured_list=()
        if declare -p WIKI_FEATURED >/dev/null 2>&1; then
            if [[ "$(declare -p WIKI_FEATURED)" == "declare -a"* ]]; then _featured_list=("${WIKI_FEATURED[@]}")
            else read -ra _featured_list <<< "$WIKI_FEATURED"; fi
        else _featured_list=("${_global_pages[@]}"); fi
        
        local -A feat_title=() feat_weight=() feat_url=()
        local -a resolved_list=()
        local fpage
        
        for fpage in "${_featured_list[@]}"; do
            local w="" t="" url=""
            
            if [[ -n "${PAGE_TITLES[$fpage]:-}" || -n "${PAGE_WEIGHTS[$fpage]:-}" ]]; then
                w="${PAGE_WEIGHTS[$fpage]:-9999}"
                t="${PAGE_TITLES[$fpage]:-}"
                url="/${fpage//./\/}.html"
            elif [[ -n "${PAGE_TITLES[${fpage}.index]:-}" || -n "${PAGE_WEIGHTS[${fpage}.index]:-}" ]]; then
                w="${PAGE_WEIGHTS[${fpage}.index]:-9999}"
                t="${PAGE_TITLES[${fpage}.index]:-}"
                url="/${fpage//./\/}/index.html"
            else
                local best_page="" best_weight=9999999 cp
                for cp in "${_pages[@]}"; do
                    if [[ "$cp" == "$fpage" || "$cp" == "${fpage}."* ]]; then
                        local cw="${PAGE_WEIGHTS[$cp]:-9999999}"
                        if (( 10#$cw < 10#$best_weight )); then
                            best_weight=$cw
                            best_page=$cp
                        elif (( 10#$cw == 10#$best_weight )); then
                            if [[ -z "$best_page" || "$cp" < "$best_page" ]]; then
                                best_page=$cp
                            fi
                        fi
                    fi
                done
                
                if [[ -n "$best_page" ]]; then
                    w="${PAGE_WEIGHTS[$best_page]:-9999}"
                    t="${PAGE_TITLES[$best_page]:-}"
                    url="/${best_page//./\/}.html"
                else
                    w=9999
                    t="${fpage##*.}"
                    t="${t^}"
                    url="/${fpage//./\/}.html"
                fi
            fi
            
            [[ -z "$t" ]] && { t="${fpage##*.}"; t="${t^}"; }
            
            feat_title["$fpage"]="$t"
            feat_weight["$fpage"]="$w"
            feat_url["$fpage"]="$url"
            
            local exists=0 r
            for r in "${resolved_list[@]}"; do
                [[ "$r" == "$fpage" ]] && { exists=1; break; }
            done
            [[ $exists -eq 0 ]] && resolved_list+=("$fpage")
        done
        
        if [ ${#resolved_list[@]} -gt 0 ]; then
            local -a raw_featured=()
            mapfile -t raw_featured < <(
                for p in "${resolved_list[@]}"; do
                    echo "${feat_weight[$p]}|$p"
                done | sort -t'|' -k1,1n -k2,2
            )
            _featured_list=()
            local item
            for item in "${raw_featured[@]}"; do
                _featured_list+=("${item##*|}")
            done
        else
            _featured_list=()
        fi
        
        WIKI_FEATURED_HTML=""
        for fpage in "${_featured_list[@]}"; do
            WIKI_FEATURED_HTML+="<a href=\"${feat_url[$fpage]}\" class=\"menu-item\">${feat_title[$fpage]}</a>"$'\n'
        done
    }
    
    __partial_menu() {
        local m_root="" m_depth="999" m_type="" m_root_label="" m_page_label="title" m_exclude="" m_closed="-1"
        if [[ $# -gt 0 ]]; then
            local str="$*"
            while [[ "$str" =~ ([a-zA-Z_]+)=([^\"\'[:space:]]+|\"([^\"]+)\"|\'([^\']+)\') ]]; do
                local key="${BASH_REMATCH[1]}"
                local val="${BASH_REMATCH[4]:-${BASH_REMATCH[3]:-${BASH_REMATCH[2]}}}"
                if [[ "$key" == "root" ]]; then m_root="$val"
                elif [[ "$key" == "depth" ]]; then m_depth="$val"
                elif [[ "$key" == "type" ]]; then m_type="$val"
                elif [[ "$key" == "root_label" ]]; then m_root_label="$val"
                elif [[ "$key" == "page_label" ]]; then m_page_label="$val"
                elif [[ "$key" == "exclude" ]]; then m_exclude="$val"
                elif [[ "$key" == "closed" ]]; then m_closed="$val"
                fi
                str="${str#*${BASH_REMATCH[0]}}"
            done
            local orig_root="$m_root"
            m_root="${m_root#/}"
            m_root="${m_root%/}"
            local prefix="${m_root//\//.}"
            [[ -n "$prefix" ]] && prefix="${prefix}."
            local c_menu="<ul class=\"sidebar-ul custom-menu\">"$'\n'
            if [[ -n "$m_root" || "$orig_root" == "/" ]]; then
                local root_node="${prefix%.}"
                local root_disp=""
                if [[ -n "$m_root_label" ]]; then
                    root_disp="$m_root_label"
                else
                    [[ -n "$root_node" ]] && root_disp="${PAGE_TITLES[$root_node]:-}"
                    [[ -z "$root_disp" ]] && root_disp="${m_root}"
                    [[ -z "$root_disp" ]] && root_disp="/"
                fi
                [[ "$root_disp" != */ ]] && root_disp="${root_disp}/"
                
                local root_open=" open"
                if (( m_closed >= 0 && 0 >= m_closed )); then root_open=""; fi
                
                c_menu+="<li class=\"sidebar-collapsible\"><details${root_open}><summary><span class=\"toggle-icon\"></span>${root_disp}</summary>"$'\n'
                c_menu+="<ul class=\"sidebar-ul-inner\">"$'\n'
            fi
            local -A seen=()
            
            local -a sorted_custom_pages=()
            local -a raw_sorted_custom=()
            mapfile -t raw_sorted_custom < <(
                local p
                for p in "${_pages[@]}"; do
                    local dir_path="${p%.*}"
                    [[ "$dir_path" == "$p" ]] && dir_path="."
                    local dw="${PAGE_WEIGHTS[${dir_path}.index]:-9999999}"
                    [[ "$dw" == "9999999" ]] && dw="${PAGE_WEIGHTS[${dir_path}]:-9999999}"
                    echo "${dw}|${dir_path}|${PAGE_WEIGHTS[$p]:-9999999}|$p"
                done | sort -t'|' -k1,1n -k2,2 -k3,3n -k4,4
            )
            local item
            for item in "${raw_sorted_custom[@]}"; do
                sorted_custom_pages+=("${item##*|}")
            done
            
            local -a current_path=()
            local p
            for p in "${sorted_custom_pages[@]}"; do
                [[ -n "$prefix" && "$p" != "${prefix}"* ]] && continue
                local rem="${p#$prefix}"
                [[ -z "$rem" ]] && continue
                
                [[ -n "$m_exclude" && $p == $m_exclude ]] && continue
                
                local prev_IFS="$IFS"
                IFS='.'
                local -a parts=($rem)
                IFS="$prev_IFS"
                
                local p_depth=${#parts[@]}
                
                local is_dir=0
                local target_depth=$p_depth
                if (( p_depth > m_depth )); then
                    target_depth=$m_depth
                    is_dir=1
                else
                    local i
                    for i in "${_pages[@]}"; do
                        if [[ "$i" == "${p}."* ]]; then is_dir=1; break; fi
                    done
                fi
                
                if [[ "$m_type" == "dir" && $is_dir -eq 0 ]]; then continue; fi
                if [[ "$m_type" == "file" && $is_dir -eq 1 ]]; then continue; fi
                
                local node_rem=""
                local j
                for ((j=0; j<target_depth; j++)); do
                    [[ -n "$node_rem" ]] && node_rem+="."
                    node_rem+="${parts[$j]}"
                done
                
                local node_full="${prefix}${node_rem}"
                if [[ -z "${seen[$node_full]:-}" ]]; then
                    seen["$node_full"]="1"
                    local disp_name=""
                    
                    if [[ "$m_page_label" == "weight" ]]; then
                        [[ -n "$node_full" ]] && disp_name="${PAGE_WEIGHTS[$node_full]:-}"
                        [[ -z "$disp_name" ]] && disp_name="9999999"
                    elif [[ "$m_page_label" == "name" ]]; then
                        disp_name="${parts[$((target_depth-1))]}"
                    else
                        [[ -n "$node_full" ]] && disp_name="${PAGE_TITLES[$node_full]:-}"
                        [[ -z "$disp_name" ]] && disp_name="${parts[$((target_depth-1))]}"
                    fi
                    
                    local page_url="${node_full//./\/}.html"
                    if [[ $is_dir -eq 1 ]]; then
                        [[ "$disp_name" != */ ]] && disp_name="${disp_name}/"
                        local best_page="" best_weight=9999999 cp
                        for cp in "${_pages[@]}"; do
                            if [[ "$cp" == "${node_full}."* ]]; then
                                local cw="${PAGE_WEIGHTS[$cp]:-9999999}"
                                if (( 10#$cw < 10#$best_weight )); then
                                    best_weight=$cw
                                    best_page=$cp
                                elif (( 10#$cw == 10#$best_weight )); then
                                    if [[ -z "$best_page" || "$cp" < "$best_page" ]]; then
                                        best_page=$cp
                                    fi
                                fi
                            fi
                        done
                        if [[ -n "$best_page" ]]; then
                            page_url="${best_page//./\/}.html"
                        else
                            page_url="${node_full//./\/}/index.html"
                        fi
                    fi
                    
                    local -a dir_parts=("${parts[@]:0:$((target_depth-1))}")
                    
                    local common_len=0
                    while [[ $common_len -lt ${#current_path[@]} && $common_len -lt ${#dir_parts[@]} && "${current_path[$common_len]}" == "${dir_parts[$common_len]}" ]]; do
                        common_len=$((common_len + 1))
                    done
                    
                    local k
                    for (( k=${#current_path[@]}-1; k>=common_len; k-- )); do 
                        c_menu+="</ul></details></li>"$'\n'
                    done
                    
                    for (( k=common_len; k<${#dir_parts[@]}; k++ )); do
                        local dir="${dir_parts[$k]}"
                        local css_class="sidebar-collapsible"
                        [[ $k -gt 0 ]] && css_class="sidebar-collapsible sub-dir"
                        
                        local current_depth=$k
                        [[ -n "$m_root" || "$orig_root" == "/" ]] && current_depth=$((k + 1))
                        
                        local dir_open=" open"
                        if (( m_closed >= 0 && current_depth >= m_closed )); then dir_open=""; fi
                        
                        c_menu+="<li class=\"${css_class}\"><details${dir_open}><summary><span class=\"toggle-icon\"></span>${dir}/</summary><ul class=\"sidebar-ul-inner\">"$'\n'
                    done
                    
                    c_menu+="<li class=\"sidebar-li\"><a href=\"/${page_url}\">${disp_name}</a></li>"$'\n'
                    
                    current_path=("${dir_parts[@]}")
                fi
            done
            
            local k
            for (( k=${#current_path[@]}-1; k>=0; k-- )); do 
                c_menu+="</ul></details></li>"$'\n'
            done
            
            if [[ -n "$m_root" || "$orig_root" == "/" ]]; then
                c_menu+="</ul></details></li>"$'\n'
            fi
            c_menu+="</ul>"$'\n'
            printf "%s" "$c_menu"
            return 0
        fi
        
        WIKI_MENU_HTML="<ul class=\"sidebar-ul\">"$'\n'
        local -a sorted_pages=()
        if [ ${#_nested_pages[@]} -gt 0 ]; then
            local -a raw_sorted=()
            mapfile -t raw_sorted < <(
                local p
                for p in "${_nested_pages[@]}"; do
                    local dir_path="${p%.*}"
                    local dw="${PAGE_WEIGHTS[${dir_path}.index]:-9999999}"
                    [[ "$dw" == "9999999" ]] && dw="${PAGE_WEIGHTS[${dir_path}]:-9999999}"
                    echo "${dw}|${dir_path}|${PAGE_WEIGHTS[$p]:-9999999}|$p"
                done | sort -t'|' -k1,1n -k2,2 -k3,3n -k4,4
            )
            local item
            for item in "${raw_sorted[@]}"; do
                sorted_pages+=("${item##*|}")
            done
        fi
        local -a current_path=()
        local idx
        for idx in "${!sorted_pages[@]}"; do
            local entry="${sorted_pages[$idx]}"
            if [[ -z "$entry" ]]; then continue; fi
            local -a parts=()
            local OIFS="$IFS"; IFS='.'; read -ra parts <<< "$entry"; IFS="$OIFS"
            local page_name="${parts[${#parts[@]}-1]}"
            local -a dir_parts=("${parts[@]:0:${#parts[@]}-1}")
            local common_len=0
            while [[ $common_len -lt ${#current_path[@]} && $common_len -lt ${#dir_parts[@]} && "${current_path[$common_len]}" == "${dir_parts[$common_len]}" ]]; do
                common_len=$((common_len + 1))
            done
            local i
            for (( i=${#current_path[@]}-1; i>=common_len; i-- )); do 
                WIKI_MENU_HTML+="</ul></details></li>"$'\n'
            done
            for (( i=common_len; i<${#dir_parts[@]}; i++ )); do
                local dir="${dir_parts[$i]}"
                local css_class="sidebar-collapsible"
                [[ $i -gt 0 ]] && css_class="sidebar-collapsible sub-dir"
                
                local dir_open=" open"
                if (( m_closed >= 0 && i >= m_closed )); then dir_open=""; fi
                
                WIKI_MENU_HTML+="<li class=\"${css_class}\"><details${dir_open}><summary><span class=\"toggle-icon\"></span>${dir}/</summary><ul class=\"sidebar-ul-inner\">"$'\n'
            done
            local page_url
            if [[ ${#dir_parts[@]} -gt 0 ]]; then
                local prev_IFS="$IFS"
                IFS='/'
                local joined="${dir_parts[*]}"
                IFS="$prev_IFS"
                page_url="${joined}/${page_name}.html"
            else
                page_url="${page_name}.html"
            fi
            local disp_name=""
            [[ -n "$entry" ]] && disp_name="${PAGE_TITLES[$entry]:-}"
            [[ -z "$disp_name" ]] && disp_name="$page_name"
            WIKI_MENU_HTML+="<li class=\"sidebar-li\"><a href=\"/${page_url}\">${disp_name}</a></li>"$'\n'
            current_path=("${dir_parts[@]}")
        done
        local i
        for (( i=${#current_path[@]}-1; i>=0; i-- )); do 
            WIKI_MENU_HTML+="</ul></details></li>"$'\n'
        done
        WIKI_MENU_HTML+="</ul>"$'\n'
    }    


    __partial_search() {
        WIKI_SEARCH_HTML="<div class=\"search-container\">"$'\n'"    <form action=\"/search.html\" method=\"GET\" class=\"search-form\" style=\"display: inline;\">"$'\n'"        <span class=\"search-input-prefix\">search:</span> <input type=\"text\" name=\"q\" id=\"search-input\" autocomplete=\"off\">"$'\n'"    </form>"$'\n'"    <div id=\"search-results\" class=\"search-popup\" style=\"display: none; position: absolute; z-index: 1000;\"></div>"$'\n'"</div>"
    }

    __partial_search_page() {
        WIKI_SEARCH_PAGE_HTML="<div class=\"search-page-container\">"$'\n'"    <form action=\"/search.html\" method=\"GET\" class=\"search-form\">"$'\n'"        <span class=\"search-input-prefix\">search:</span> <input type=\"text\" name=\"q\" id=\"search-page-input\" autocomplete=\"off\">"$'\n'"    </form>"$'\n'"    <div id=\"search-page-results\" class=\"search-inline\"></div>"$'\n'"</div>"
    }   

    __partial_breadcrumb() {
        local b_root_label="Home"
        local b_page_label="title"
        local b_sep="/"
        local str="$*"
        while [[ "$str" =~ ([a-zA-Z_]+)=([^\"\'[:space:]]+|\"([^\"]+)\"|\'([^\']+)\') ]]; do
            local key="${BASH_REMATCH[1]}"
            local val="${BASH_REMATCH[4]:-${BASH_REMATCH[3]:-${BASH_REMATCH[2]}}}"
            if [[ "$key" == "root_label" ]]; then b_root_label="$val"
            elif [[ "$key" == "page_label" || "$key" == "label" ]]; then b_page_label="$val"
            elif [[ "$key" == "sep" ]]; then b_sep="$val"
            fi
            str="${str#*${BASH_REMATCH[0]}}"
        done
        local out="<breadcrumb><a href=\"/index.html\" class=\"breadcrumb-0\">${b_root_label}</a>"
        local -a b_parts=()
        local OIFS="$IFS"; IFS='.'; read -ra b_parts <<< "$pagename"; IFS="$OIFS"
        local cum_slug=""
        local i
        for ((i=0; i<${#b_parts[@]}; i++)); do
            local part="${b_parts[$i]}"
            if [[ -z "$cum_slug" ]]; then cum_slug="$part"; else cum_slug="${cum_slug}.${part}"; fi
            local b_title=""
            if [[ "$b_page_label" == "name" ]]; then
                b_title="$part"
            elif [[ "$b_page_label" == "weight" ]]; then
                b_title="${PAGE_WEIGHTS[$cum_slug]:-9999}"
            else
                b_title="${PAGE_TITLES[$cum_slug]:-$part}"
            fi
            local b_idx=$((i + 1))
            if [[ $i -eq $((${#b_parts[@]} - 1)) ]]; then
                out+="<span class=\"breadcrumb-sep\">${b_sep}</span><a href=\"/${cum_slug//./\/}.html\" class=\"breadcrumb-current\">${b_title}</a>"
            else
                local dir_path="${cum_slug//./\/}"
                if [[ -f "$SOURCEDIR/$dir_path/index.md" ]]; then
                    out+="<span class=\"breadcrumb-sep\">${b_sep}</span><a href=\"/${dir_path}/index.html\" class=\"breadcrumb-${b_idx}\">${b_title}</a>"
                elif [[ -f "$SOURCEDIR/${dir_path}.md" ]]; then
                    out+="<span class=\"breadcrumb-sep\">${b_sep}</span><a href=\"/${dir_path}.html\" class=\"breadcrumb-${b_idx}\">${b_title}</a>"
                else
                    local best_page=""
                    local best_weight=9999999
                    local p
                    for p in "${_pages[@]}"; do
                        if [[ "$p" == "${cum_slug}."* ]]; then
                            local remainder="${p#${cum_slug}.}"
                            if [[ "$remainder" != *.* ]]; then
                                local w="${PAGE_WEIGHTS[$p]}"
                                [[ -z "$w" ]] && w=9999999
                                if (( 10#$w < 10#$best_weight )); then
                                    best_weight=$w
                                    best_page="$p"
                                elif (( 10#$w == 10#$best_weight )); then
                                    if [[ -z "$best_page" ]] || [[ "$p" < "$best_page" ]]; then
                                        best_page="$p"
                                    fi
                                fi
                            fi
                        fi
                    done
                    if [[ -n "$best_page" ]]; then
                        out+="<span class=\"breadcrumb-sep\">${b_sep}</span><a href=\"/${best_page//./\/}.html\" class=\"breadcrumb-${b_idx}\">${b_title}</a>"
                    else
                        out+="<span class=\"breadcrumb-sep\">${b_sep}</span><span class=\"breadcrumb-${b_idx}\">${b_title}</span>"
                    fi
                fi
            fi
        done
        out+="</breadcrumb>"
        printf "%s" "$out"
    }   

    __partial_thumb() {
        WIKI_THUMB_HTML=""
        local in_globals=0 g_line t_img
        while IFS= read -r g_line || [[ -n "$g_line" ]]; do
            g_line="${g_line%$'\r'}"
            if (( in_globals == 0 )); then
                [[ "$g_line" =~ ^[[:space:]]*\{\{[[:space:]]*block\.globals[[:space:]]*\}\}[[:space:]]*$ ]] && in_globals=1
            else
                [[ "$g_line" =~ ^[[:space:]]*\{\{[[:space:]]*block\.end[[:space:]]*\}\}[[:space:]]*$ ]] && break
                if [[ "$g_line" =~ ^[[:space:]]*::[[:space:]]*thumb:[[:space:]]*(.*)$ ]]; then
                    t_img="${BASH_REMATCH[1]}"
                    t_img="${t_img#"${t_img%%[![:space:]]*}"}"
                    t_img="${t_img%"${t_img##*[![:space:]]}"}"
                    if [[ -n "$t_img" ]]; then
                        if [[ "$t_img" != http://* && "$t_img" != https://* && "$t_img" != /* ]]; then
                            t_img="/_static/${t_img}"
                        fi
                        WIKI_THUMB_HTML="<figure class=\"block-image\" style=\"display: flex; flex-direction: column; align-items: center; justify-content: center; text-align: center;\">"$'\n'
                        WIKI_THUMB_HTML+="    <img src=\"${t_img}\" alt=\"\" class=\"block-image-img\" style=\"width: inherit;\">"$'\n'
                        WIKI_THUMB_HTML+="</figure>"
                    fi
                fi
            fi
        done < "$file"
    }

    __partial_tags() {
        local t_prefix="tags:"
        local str="$*"
        while [[ "$str" =~ ([a-zA-Z_]+)=([^\"\'[:space:]]+|\"([^\"]+)\"|\'([^\']+)\') ]]; do
            local key="${BASH_REMATCH[1]}"
            local val="${BASH_REMATCH[4]:-${BASH_REMATCH[3]:-${BASH_REMATCH[2]}}}"
            if [[ "$key" == "prefix" ]]; then t_prefix="$val"; fi
            str="${str#*${BASH_REMATCH[0]}}"
        done

        WIKI_TAGS_HTML=""
        local in_globals=0 g_line t_tags old_ifs t
        local -a tag_arr
        while IFS= read -r g_line || [[ -n "$g_line" ]]; do
            g_line="${g_line%$'\r'}"
            if (( in_globals == 0 )); then
                [[ "$g_line" =~ ^[[:space:]]*\{\{[[:space:]]*block\.globals[[:space:]]*\}\}[[:space:]]*$ ]] && in_globals=1
            else
                [[ "$g_line" =~ ^[[:space:]]*\{\{[[:space:]]*block\.end[[:space:]]*\}\}[[:space:]]*$ ]] && break
                if [[ "$g_line" =~ ^[[:space:]]*::[[:space:]]*tags:[[:space:]]*(.*)$ ]]; then
                    t_tags="${BASH_REMATCH[1]}"
                    t_tags="${t_tags#"${t_tags%%[![:space:]]*}"}"
                    t_tags="${t_tags%"${t_tags##*[![:space:]]}"}"
                    if [[ -n "$t_tags" ]]; then
                        WIKI_TAGS_HTML="<tags>"$'\n'
                        WIKI_TAGS_HTML+="<prefix class=\"tags-prefix\">${t_prefix}</prefix>"$'\n'
                        old_ifs="$IFS"
                        IFS=","
                        tag_arr=($t_tags)
                        IFS="$old_ifs"
                        for t in "${tag_arr[@]}"; do
                            t="${t#"${t%%[![:space:]]*}"}"
                            t="${t%"${t##*[![:space:]]}"}"
                            [[ -z "$t" ]] && continue
                            WIKI_TAGS_HTML+="<tag><a href=\"/search.html?q=tag:${t}\">${t}</a></tag>"$'\n'
                        done
                        WIKI_TAGS_HTML+="</tags>"
                    fi
                fi
            fi
        done < "$file"
    }

    __partial_related() {
        local title="" args=""
        local str="$*"
        while [[ "$str" =~ ([a-zA-Z_.-]+)=([^\"\'[:space:]]+|\"([^\"]+)\"|\'([^\']+)\') ]]; do
            local key="${BASH_REMATCH[1]}"
            local val="${BASH_REMATCH[4]:-${BASH_REMATCH[3]:-${BASH_REMATCH[2]}}}"
            if [[ "$key" == "title" ]]; then
                title="$val"
            else
                args+=" ${key}=\"${val}\""
            fi
            str="${str#*${BASH_REMATCH[0]}}"
        done

        local in_globals=0 g_line
        while IFS= read -r g_line || [[ -n "$g_line" ]]; do
            g_line="${g_line%$'\r'}"
            if (( in_globals == 0 )); then
                [[ "$g_line" =~ ^[[:space:]]*\{\{[[:space:]]*block\.globals[[:space:]]*\}\}[[:space:]]*$ ]] && in_globals=1
            else
                [[ "$g_line" =~ ^[[:space:]]*\{\{[[:space:]]*block\.end[[:space:]]*\}\}[[:space:]]*$ ]] && break
                if [[ "$g_line" =~ ^[[:space:]]*::[[:space:]]*related:[[:space:]]*(.*)$ ]]; then
                    local rel_val="${BASH_REMATCH[1]}"
                    rel_val="${rel_val#"${rel_val%%[![:space:]]*}"}"
                    rel_val="${rel_val%"${rel_val##*[![:space:]]}"}"
                    [[ -n "$rel_val" ]] && args+=" ${rel_val}"
                fi
            fi
        done < "$file"

        local out=""
        [[ -n "$title" ]] && out+="<h1>${title}</h1>"$'\n'
        out+="$(__listing_pages $args)"
        printf "%s" "$out"
    }

    __partial_head() {
        local h_title="" h_css="" h_js="" h_thumb=""
        local str="$*"
        while [[ "$str" =~ ([a-zA-Z_.-]+)=([^\"\'[:space:]]+|\"([^\"]+)\"|\'([^\']+)\') ]]; do
            local key="${BASH_REMATCH[1]}"
            local val="${BASH_REMATCH[4]:-${BASH_REMATCH[3]:-${BASH_REMATCH[2]}}}"
            
            [[ "$val" == page.* ]] && val="${PAGE_VARS[$val]}"
            
            if [[ "$key" == "title" ]]; then h_title="$val"
            elif [[ "$key" == "css" ]]; then h_css="$val"
            elif [[ "$key" == "js" ]]; then h_js="$val"
            elif [[ "$key" == "thumb" ]]; then h_thumb="$val"
            fi
            str="${str#*${BASH_REMATCH[0]}}"
        done

        if [[ -n "$h_thumb" && "$h_thumb" != http://* && "$h_thumb" != https://* && "$h_thumb" != /* ]]; then
            h_thumb="/_static/${h_thumb}"
        fi

        local out="<meta charset=\"UTF-8\">"$'\n'
        out+="<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"$'\n'
        out+="<title>${h_title}</title>"$'\n'
        out+="<link rel=\"stylesheet\" href=\"${h_css}\">"$'\n'
        out+="<link rel=\"icon\" type=\"image/png\" href=\"/_static/favicon/favicon-96x96.png\" sizes=\"96x96\">"$'\n'
        out+="<link rel=\"icon\" type=\"image/svg+xml\" href=\"/_static/favicon/favicon.svg\">"$'\n'
        out+="<link rel=\"shortcut icon\" href=\"/_static/favicon/favicon.ico\">"$'\n'
        out+="<link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"/_static/favicon/apple-touch-icon.png\">"$'\n'
        out+="<meta name=\"apple-mobile-web-app-title\" content=\"ximenesyuri\">"$'\n'
        out+="<link rel=\"manifest\" href=\"/_static/favicon/site.webmanifest\">"$'\n'
        out+="<script type=\"module\" src=\"${h_js}\"></script>"$'\n'

        if [[ -n "$h_thumb" ]]; then
            out+="<meta property=\"og:title\" content=\"${h_title}\">"$'\n'
            out+="<meta property=\"og:image\" content=\"${h_thumb}\">"$'\n'
            out+="<meta name=\"twitter:card\" content=\"summary_large_image\">"$'\n'
            out+="<meta name=\"twitter:title\" content=\"${h_title}\">"$'\n'
            out+="<meta name=\"twitter:image\" content=\"${h_thumb}\">"$'\n'
        fi

        out+="<script>
        document.addEventListener('DOMContentLoaded', async function() {
            if (window.matchMedia(\"(max-width: 768px)\").matches) {
                document.querySelectorAll('.sidebar-collapsible > details[open]').forEach(function(details){
                    details.removeAttribute('open');
                });
            }
            wiki.full(true);
        });
    </script>"$'\n'

        out+="</head>"
        printf "%s" "$out"
    }
}
