#! /bin/bash

__render__() {

    __render_listings () {
        TOC_HTML+="</ul>"
        local FILES_HTML="<ul class=\"dir-files\">"$'\n'"${DIR_FILES_MAP[$current_dir]:-}"$'\n'"</ul>"
        content="${content//\{\{TOC_PLACEHOLDER\}\}/$TOC_HTML}"
        content="${content//\{\{FILES_PLACEHOLDER\}\}/$FILES_HTML}"
        
        while [[ "$content" =~ \{\{[[:space:]]*list\.pages([[:space:]]+([^}]+))?[[:space:]]*\}\} ]]; do
            local full_match="${BASH_REMATCH[0]}"
            local args="${BASH_REMATCH[2]:-}"
            local l_root="$current_dir"
            local l_pattern="*"
            local -A l_globals_and=()
            local -A l_globals_or=()
            
            local str="$args"
            while [[ "$str" =~ ([a-zA-Z0-9_.-]+)=([^\"][^[:space:]]*|\"([^\"]+)\") ]]; do
                local key="${BASH_REMATCH[1]}"
                local val="${BASH_REMATCH[3]:-${BASH_REMATCH[2]}}"
                val="${val%\"}"; val="${val#\"}"
                
                if [[ "$key" == "root" ]]; then l_root="$val"
                elif [[ "$key" == "pattern" ]]; then l_pattern="$val"
                elif [[ "$key" == globals.* ]]; then
                    local g_key="${key#globals.}"
                    if [[ "$val" == *" AND "* ]]; then
                        l_globals_and["$g_key"]="$val"
                    else
                        l_globals_or["$g_key"]="$val"
                    fi
                fi
                str="${str#*${BASH_REMATCH[0]}}"
            done
            
            [[ "$l_root" == "." || -z "$l_root" ]] && l_root=""
            
            local list_html="<list class=\"list-pages\">"$'\n'"<ul class=\"list-pages-ul\">"$'\n'
            
            local target_dir="$SOURCEDIR"
            if [[ -n "$l_root" ]]; then
                if [[ "$l_root" == /* ]]; then
                    target_dir="$SOURCEDIR${l_root}"
                else
                    target_dir="$SOURCEDIR/${l_root//./\/}"
                fi
            fi
            
            if [[ -d "$target_dir" ]]; then
                local f
                for f in "$target_dir"/$l_pattern; do
                    [[ -f "$f" ]] || continue
                    
                    local match=1
                    if [[ ${#l_globals_and[@]} -gt 0 || ${#l_globals_or[@]} -gt 0 ]]; then
                        local in_globals=0
                        local -A file_globals=()
                        while IFS= read -r g_line || [[ -n "$g_line" ]]; do
                            g_line="${g_line%$'\r'}"
                            if (( in_globals == 0 )); then
                                [[ "$g_line" =~ ^[[:space:]]*\{\{[[:space:]]*block\.globals[[:space:]]*\}\}[[:space:]]*$ ]] && in_globals=1
                            else
                                [[ "$g_line" =~ ^[[:space:]]*\{\{[[:space:]]*block\.end[[:space:]]*\}\}[[:space:]]*$ ]] && break
                                if [[ "$g_line" =~ ^[[:space:]]*::[[:space:]]*([a-zA-Z0-9_-]+):[[:space:]]*(.*)$ ]]; then
                                    file_globals["${BASH_REMATCH[1]}"]="${BASH_REMATCH[2]}"
                                fi
                            fi
                        done < "$f"
                        
                        local gk actual_v
                        for gk in "${!l_globals_and[@]}"; do
                            actual_v="${file_globals[$gk]:-}"
                            if [[ -z "$actual_v" ]]; then match=0; break; fi
                            local old_ifs="$IFS"; IFS=" AND "; local -a req_arr=(${l_globals_and[$gk]}); IFS="$old_ifs"
                            local req_v
                            for req_v in "${req_arr[@]}"; do
                                if [[ "$req_v" != "AND" && -n "${req_v// /}" ]]; then
                                    req_v="${req_v#"${req_v%%[![:space:]]*}"}"; req_v="${req_v%"${req_v##*[![:space:]]}"}"
                                    if [[ $actual_v != *$req_v* ]]; then match=0; break; fi
                                fi
                            done
                            (( match == 0 )) && break
                        done
                        
                        if (( match == 1 )); then
                            for gk in "${!l_globals_or[@]}"; do
                                actual_v="${file_globals[$gk]:-}"
                                if [[ -z "$actual_v" ]]; then match=0; break; fi
                                local or_match=0
                                local old_ifs="$IFS"; IFS=" OR "; local -a req_arr=(${l_globals_or[$gk]}); IFS="$old_ifs"
                                local req_v
                                for req_v in "${req_arr[@]}"; do
                                    if [[ "$req_v" != "OR" && -n "${req_v// /}" ]]; then
                                        req_v="${req_v#"${req_v%%[![:space:]]*}"}"; req_v="${req_v%"${req_v##*[![:space:]]}"}"
                                        if [[ $actual_v == *$req_v* ]]; then or_match=1; break; fi
                                    fi
                                done
                                if (( or_match == 0 )); then match=0; break; fi
                            done
                        fi
                    fi
                    
                    if (( match == 1 )); then
                        local fname="${f##*/}"
                        local p_url="" slug_key=""
                        if [[ -n "$l_root" ]]; then
                            p_url="${l_root//./\/}/${fname%.*}.html"
                            slug_key="${l_root//\//.}.${fname%.*}"
                        else
                            p_url="${fname%.*}.html"
                            slug_key="${fname%.*}"
                        fi
                        [[ "$p_url" != /* ]] && p_url="/${p_url}"
                        p_url="${p_url//\/\//\/}"
                        slug_key="${slug_key#.}"
                        
                        local disp_name="${PAGE_TITLES[$slug_key]:-${fname%.*}}"
                        list_html+="<li class=\"list-pages-li\"><a href=\"$p_url\">$disp_name</a></li>"$'\n'
                    fi
                done
            fi
            list_html+="</ul>"$'\n'"</list>"
            content="${content//"$full_match"/$list_html}"
        done
        
        while [[ "$content" =~ \{\{[[:space:]]*list\.([a-zA-Z0-9_-]+)(:([^}[:space:]]+))?[[:space:]]*\}\} ]]; do
            local full_match="${BASH_REMATCH[0]}"
            local l_type="${BASH_REMATCH[1]}"
            local l_path="${BASH_REMATCH[3]}"
            local singular="${l_type%s}"
            local b_name="$l_type"
            if [[ -n "${LIST_HTML_MAP[$singular]:-}" ]]; then b_name="$singular"; fi
            local list_html="<list class=\"list-${l_type}\">"$'\n'"<ul class=\"list-${l_type}-ul\">"$'\n'
            
            if [[ -z "$l_path" ]]; then
                local injected="${LIST_HTML_MAP[$b_name]:-}"
                injected="${injected//<li>/<li class=\"list-${l_type}-li\">}"
                list_html+="${injected}"
            else
                local target_file=""
                if [[ "$l_path" == /* ]]; then target_file="$SOURCEDIR${l_path}"
                else target_file="$SOURCEDIR/${current_dir//./\/}/${l_path}"; fi
                [[ "$target_file" != *.md ]] && target_file="${target_file}.md"
                
                local t_dir="${target_file%/*}"
                local t_base="${target_file##*/}"
                if [[ -d "$t_dir" ]]; then
                    t_dir="$(cd "$t_dir" 2>/dev/null && pwd)"
                    target_file="${t_dir}/${t_base}"
                fi
                
                if [[ -f "$target_file" ]]; then
                    local t_rel="${target_file#$SOURCEDIR/}"
                    local t_url="/${t_rel%.md}.html"
                    local in_block="" block_id="" first_key="" first_val=""
                    local item_count=0
                    local -a t_buffer=()
                    while IFS= read -r t_line || [[ -n "$t_line" ]]; do
                        t_line="${t_line%$'\r'}"
                        if [[ -z "$in_block" ]]; then
                            if [[ "$t_line" =~ ^[[:space:]]*\{\{[[:space:]]*block\.([a-zA-Z0-9_-]+)[[:space:]]*\}\}[[:space:]]*$ ]]; then
                                in_block="${BASH_REMATCH[1]}"
                                block_id="" first_key="" first_val=""
                                if [[ "$in_block" == "table" ]]; then t_buffer=(); fi
                            fi
                        else
                            if [[ "$t_line" =~ ^[[:space:]]*\{\{[[:space:]]*block\.end[[:space:]]*\}\}[[:space:]]*$ ]]; then
                                if [[ "$in_block" == "table" ]]; then
                                    ((item_count++))
                                    local caption="" sep_count=0 i
                                    for ((i=0; i<${#t_buffer[@]}; i++)); do
                                        if [[ "${t_buffer[$i]}" =~ ^[-=_]{4,} ]]; then ((sep_count++)); fi
                                    done
                                    if [[ $sep_count -ge 2 ]]; then
                                        local found_sep=0
                                        for ((i=0; i<${#t_buffer[@]}; i++)); do
                                            if [[ "${t_buffer[$i]}" =~ ^[-=_]{4,} ]]; then ((found_sep++)); continue; fi
                                            if [[ $found_sep -eq $sep_count ]]; then
                                                local cl="${t_buffer[$i]}"
                                                cl="${cl#"${cl%%[![:space:]]*}"}"; cl="${cl%"${cl##*[![:space:]]}"}"
                                                if [[ -n "$cl" ]]; then caption="$cl"; break; fi
                                            fi
                                        done
                                    fi
                                    list_html+="<li class=\"list-${l_type}-li\"><a href=\"${t_url}#table-${item_count}\">${caption:-Table ${item_count}}</a></li>"$'\n'
                                elif [[ "$in_block" == "diagram" ]]; then
                                    ((item_count++))
                                    list_html+="<li class=\"list-${l_type}-li\"><a href=\"${t_url}#diagram-${item_count}\">Diagram ${item_count}</a></li>"$'\n'
                                elif [[ "$in_block" == "$b_name" || "$in_block" == "$l_type" ]]; then
                                    local b_id="${block_id:-$(__slugify "$first_val")}"
                                    local anchor_id="block-${in_block}-${b_id}"
                                    list_html+="<li class=\"list-${l_type}-li\"><a href=\"${t_url}#${anchor_id}\">$first_val</a></li>"$'\n'
                                fi
                                in_block=""
                            else
                                if [[ "$in_block" == "table" ]]; then
                                    t_buffer+=("$t_line")
                                elif [[ "$t_line" =~ ^[[:space:]]*::[[:space:]]*([a-zA-Z0-9_-]+):[[:space:]]*(.*)$ ]]; then
                                    local k="${BASH_REMATCH[1]}" v="${BASH_REMATCH[2]}"
                                    v="${v#"${v%%[![:space:]]*}"}"; v="${v%"${v##*[![:space:]]}"}"
                                    if [[ "$k" == "__id__" ]]; then block_id="$v"; fi
                                    if [[ -z "$first_key" && "$k" != "__id__" ]]; then
                                        first_key="$k"; first_val="$v"
                                    fi
                                fi
                            fi
                        fi
                    done < "$target_file"
                else
                    list_html+="<li class=\"list-${l_type}-li\"><span class=\"wiki-ref-err\">File not found: ${l_path}</span></li>"$'\n'
                fi
            fi
            list_html+="</ul>"$'\n'"</list>"
            content="${content//"$full_match"/$list_html}"
        done
    }

    __render_layout() {
        local PAGE_LAYOUT="" skip=0 ll
        for ll in "${layout_lines[@]}"; do
            if [[ "$ll" == *"{%"* ]]; then
                if [[ "$ll" =~ \{\%\ *if\ *\'([^\']+)\'\ *in\ *page\.name\ *and\ *not\ *page\.name\ *==\ *\"([^\"]+)\"\ *\%\} ]]; then
                    if [[ "$pagename" == *"${BASH_REMATCH[1]}"* && "$pagename" != "${BASH_REMATCH[2]}" ]]; then skip=0; else skip=1; fi
                    continue
                fi
                if [[ "$ll" =~ \{\%\ *if\ *\'([^\']+)\'\ *in\ *page\.name\ *\%\} ]]; then
                    if [[ "$pagename" == *"${BASH_REMATCH[1]}"* ]]; then skip=0; else skip=1; fi
                    continue
                fi
                if [[ "$ll" =~ \{\%\ *else\ *\%\} ]]; then
                    if [[ $skip -eq 0 ]]; then skip=1; else skip=0; fi
                    continue
                fi
                if [[ "$ll" =~ \{\%\ *endif\ *\%\} ]]; then
                    skip=0
                    continue
                fi
                if [[ "$ll" =~ \{\%\ *(for|from|include|endfor).*\%\} ]]; then continue; fi
            fi
            if (( skip == 1 )); then continue; fi
            if [[ "$ll" == *"{{ render_menu_item"* || "$ll" == *"{{ item"* ]]; then continue; fi
            if [[ "$ll" == *"{{ page."* ]]; then
                while [[ "$ll" =~ \{\{\ *page\.([a-zA-Z0-9_.-]+)\ *\}\} ]]; do
                    local full_match="${BASH_REMATCH[0]}"
                    local suffix="${BASH_REMATCH[1]}"
                    if [[ "$suffix" == "name" || "$suffix" == "body" || "$suffix" == "title" ]]; then
                        ll="${ll/"$full_match"/%%RETAIN_PAGE_${suffix}%%}"
                    else
                        local var_name="page.${suffix}"
                        local val="${PAGE_VARS[$var_name]}"
                        ll="${ll//"$full_match"/$val}"
                    fi
                done
                local pnt="{{ page.name }}"
                local pbt="{{ page.body }}"
                local ptt="{{ page.title }}"
                ll="${ll//%%RETAIN_PAGE_name%%/$pnt}"
                ll="${ll//%%RETAIN_PAGE_body%%/$pbt}"
                ll="${ll//%%RETAIN_PAGE_title%%/$ptt}"
            fi
            if [[ "$ll" == *"{{ wiki.frontmatter."* ]]; then
                while [[ "$ll" =~ \{\{\ *wiki\.frontmatter\.([a-zA-Z0-9_.-]+)\ *\}\} ]]; do
                    local full_match="${BASH_REMATCH[0]}"
                    local var_name="page.${BASH_REMATCH[1]}"
                    local val="${PAGE_VARS[$var_name]}"
                    ll="${ll//"$full_match"/$val}"
                done
            fi
            PAGE_LAYOUT+="$ll"$'\n'
        done
        
        rendered="$PAGE_LAYOUT"
        while [[ "$rendered" =~ \{\{[[:space:]]*(wiki\.)?menu[[:space:]]+([^}]+)\}\} ]]; do
            local full_match="${BASH_REMATCH[0]}"
            local args="${BASH_REMATCH[2]}"
            local custom_menu="$(__partial_menu $args)"
            rendered="${rendered/"$full_match"/$custom_menu}"
        done

        while [[ "$rendered" =~ \{\{[[:space:]]*(wiki\.)?breadcrumb[[:space:]]*([^}]*)\}\} ]]; do
            local full_match="${BASH_REMATCH[0]}"
            local args="${BASH_REMATCH[2]}"
            local custom_bc="$(__partial_breadcrumb $args)"
            rendered="${rendered/"$full_match"/$custom_bc}"
        done
        
        local search_tags=("{{ page.body }}" "{{page.body}}" "{{ page.name }}" "{{page.name}}" "{{ page.title }}" "{{page.title}}" "{{ wiki.menu }}" "{{wiki.menu}}" "{{ menu }}" "{{menu}}" "{{ wiki.featured }}" "{{wiki.featured}}" "{{ datetime.year }}" "{{datetime.year}}" "{{ datetime.now }}" "{{datetime.now}}" "{{ wiki.search }}" "{{wiki.search}}" "{{ wiki.search_page }}" "{{wiki.search_page}}" "{{ wiki.thumb }}" "{{wiki.thumb}}" "{{ wiki.tags }}" "{{wiki.tags}}")
        
        local year now t_val=""
        printf -v year "%(%Y)T" -1
        printf -v now "%(%Y/%m/%d at %H:%M)T" -1
        
        local WIKI_SEARCH_HTML="" WIKI_SEARCH_PAGE_HTML="" WIKI_THUMB_HTML="" WIKI_TAGS_HTML=""
        __partial_search
        __partial_search_page
        __partial_thumb
        __partial_tags
        
        for search in "${search_tags[@]}"; do
            case "$search" in
                "{{ page.body }}"|"{{page.body}}") t_val="$content" ;;
                "{{ page.name }}"|"{{page.name}}") t_val="$title" ;;
                "{{ page.title }}"|"{{page.title}}") t_val="${PAGE_TITLES[$pagename]:-$pagename}" ;;
                "{{ wiki.menu }}"|"{{wiki.menu}}"|"{{ menu }}"|"{{menu}}") t_val="$WIKI_MENU_HTML" ;;
                "{{ wiki.featured }}"|"{{wiki.featured}}"|"{{ featured }}"|"{{featured}}") t_val="$WIKI_FEATURED_HTML" ;;
                "{{ datetime.year }}"|"{{datetime.year}}") t_val="$year" ;;
                "{{ datetime.now }}"|"{{datetime.now}}") t_val="$now" ;;
                "{{ wiki.search }}"|"{{wiki.search}}") t_val="$WIKI_SEARCH_HTML" ;;
                "{{ wiki.search_page }}"|"{{wiki.search_page}}") t_val="$WIKI_SEARCH_PAGE_HTML" ;;
                "{{ wiki.thumb }}"|"{{wiki.thumb}}") t_val="$WIKI_THUMB_HTML" ;;
                "{{ wiki.tags }}"|"{{wiki.tags}}") t_val="$WIKI_TAGS_HTML" ;;
            esac
            rendered="${rendered//"$search"/$t_val}"
        done
        local auto_js="<script>%%WIKI_SEARCH_CONFIG%%; if (typeof hljs !== 'undefined') hljs.highlightAll();</script>"
        if [[ "$rendered" == *"</body>"* ]]; then
            rendered="${rendered/<\/body>/$auto_js$'\n'<\/body>}"
        else
            rendered+="$auto_js"$'\n'
        fi
    }    

    __render_main() {
        local file="$1" pagename="$2" out_path="$3" current_dir="$4"
        local h_regex='^(#{1,6})\ +(.*)'
        local _amp="&amp;" _lt="&lt;" _gt="&gt;"
        if shopt -q patsub_replacement 2>/dev/null; then _amp="\\&amp;"; _lt="\\&lt;"; _gt="\\&gt;"; fi
        local content="" rendered="" in_frontmatter=0 title="$pagename" TOC_HTML="<ul class=\"toc\">"$'\n'
        local page_table_count=0 page_diagram_count=0
        local in_code_block=0 in_html_pre=0 in_custom_block="" custom_block_indent="" list_depth=0 was_empty=0 ignore_next_empty=0 set_ignore_this_turn=0 line
        local -a table_buffer=() diagram_buffer=() custom_block_buffer=() hide_buffer=() KEYS_STACK=() LIST_INDENTS=() LIST_TYPES=() lines=()
        local -A PAGE_VARS=()
        mapfile -t lines < "$file"
        __parse_main
        __render_listings
        __search_index
        __render_layout
        local ref_re='%%WIKI_REF:([^:]+):([^:]+):([^%]+)%%'
        while [[ "$rendered" =~ $ref_re ]]; do
            local full="${BASH_REMATCH[0]}"
            local topic="${BASH_REMATCH[1]}"
            local ref_key="${BASH_REMATCH[2]}"
            local label="${BASH_REMATCH[3]}"
            local key="${topic}::${ref_key}"
            local target="${WIKI_REFS[$key]:-}"
            if [[ -z "$target" && -n "$w_name" ]]; then
                target="${WIKI_REFS[${w_name}::${ENV:-}::${key}]:-}"
            fi
            if [[ -z "$target" ]]; then
                local clean_key="${key//[^a-zA-Z0-9_.:-]/}"
                local k
                for k in "${!WIKI_REFS[@]}"; do
                    local clean_k="${k//[^a-zA-Z0-9_.:-]/}"
                    if [[ "$clean_k" == "$clean_key" || "$clean_k" == *"::${clean_key}" ]]; then
                        target="${WIKI_REFS[$k]}"
                        break
                    fi
                done
            fi
            if [[ -z "$target" ]]; then
                rendered="${rendered//"$full"/<span class=\"wiki-ref-err\">${label}</span>}"
            else
                local href=""
                if [[ "$target" == http://* || "$target" == https://* ]]; then href="$target"
                else
                    local internal_path="${target%:*}" marker="${target##*:}"
                    [[ "$target" != *":"* ]] && marker=""
                    internal_path="${internal_path//./\/}"; href="/${internal_path}.html"
                    [[ -n "$marker" ]] && href="${href}#${marker}"
                fi
                rendered="${rendered//"$full"/<a class=\"wiki-topic-${topic}\" href=\"${href}\">${label}</a>}"
            fi
        done
        printf "%s" "$rendered" > "$out_path"
        __log "Rendered -> $out_path" -t success -l wiki
    }

}
