#! /bin/bash

__render__() {

    __render_listings () {
        TOC_HTML+="</ul>"
        local FILES_HTML="<ul class=\"dir-files\">"$'\n'"${DIR_FILES_MAP[$current_dir]}"$'\n'"</ul>"
        content="${content//\{\{TOC_PLACEHOLDER\}\}/$TOC_HTML}"
        content="${content//\{\{FILES_PLACEHOLDER\}\}/$FILES_HTML}"
        while [[ "$content" =~ \{\{[[:space:]]*list\.([a-zA-Z0-9_-]+)(:([^}[:space:]]+))?[[:space:]]*\}\} ]]; do
            local full_match="${BASH_REMATCH[0]}"
            local l_type="${BASH_REMATCH[1]}"
            local l_path="${BASH_REMATCH[3]}"
            local singular="${l_type%s}"
            local b_name="$l_type"
            if [[ -n "${LIST_HTML_MAP[$singular]:-}" ]]; then b_name="$singular"; fi
            local list_html="<ul class=\"list-${l_type}\">"$'\n'
            if [[ -z "$l_path" ]]; then
                list_html+="${LIST_HTML_MAP[$b_name]:-}"
            else
                local target_file=""
                if [[ "$l_path" == /* ]]; then target_file="$SOURCEDIR${l_path}"
                else target_file="$SOURCEDIR/$current_dir/${l_path}"; fi
                [[ "$target_file" != *.md ]] && target_file="${target_file}.md"
                local t_dir="$(dirname "$target_file")"
                local t_base="$(basename "$target_file")"
                if [[ -d "$t_dir" ]]; then
                    t_dir="$(cd "$t_dir" 2>/dev/null && pwd)"
                    target_file="${t_dir}/${t_base}"
                fi
                if [[ -f "$target_file" ]]; then
                    local t_rel="${target_file#$SOURCEDIR/}"
                    local t_url="/${t_rel%.md}.html"
                    local in_block="" block_id="" first_key="" first_val=""
                    local item_count=0
                    local -a t_buffer=()
                    while IFS= read -r t_line || [[ -n "$t_line" ]]; do
                        t_line="${t_line%$'\r'}"
                        if [[ -z "$in_block" ]]; then
                            if [[ "$t_line" =~ ^[[:space:]]*\{\{[[:space:]]*block\.([a-zA-Z0-9_-]+)[[:space:]]*\}\}[[:space:]]*$ ]]; then
                                in_block="${BASH_REMATCH[1]}"
                                block_id=""
                                first_key=""
                                first_val=""
                                if [[ "$in_block" == "table" ]]; then t_buffer=(); fi
                            fi
                        else
                            if [[ "$t_line" =~ ^[[:space:]]*\{\{[[:space:]]*block\.end[[:space:]]*\}\}[[:space:]]*$ ]]; then
                                if [[ "$in_block" == "table" ]]; then
                                    ((item_count++))
                                    local caption="" sep_count=0 i
                                    for ((i=0; i<${#t_buffer[@]}; i++)); do
                                        if [[ "${t_buffer[$i]}" =~ ^[-=_]{4,} ]]; then ((sep_count++)); fi
                                    done
                                    if [[ $sep_count -ge 2 ]]; then
                                        local found_sep=0
                                        for ((i=0; i<${#t_buffer[@]}; i++)); do
                                            if [[ "${t_buffer[$i]}" =~ ^[-=_]{4,} ]]; then ((found_sep++)); continue; fi
                                            if [[ $found_sep -eq $sep_count ]]; then
                                                local cl="${t_buffer[$i]}"
                                                cl="${cl#"${cl%%[![:space:]]*}"}"; cl="${cl%"${cl##*[![:space:]]}"}"
                                                if [[ -n "$cl" ]]; then caption="$cl"; break; fi
                                            fi
                                        done
                                    fi
                                    list_html+="<li><a href=\"${t_url}#table-${item_count}\">${caption:-Table ${item_count}}</a></li>"$'\n'
                                elif [[ "$in_block" == "diagram" ]]; then
                                    ((item_count++))
                                    list_html+="<li><a href=\"${t_url}#diagram-${item_count}\">Diagram ${item_count}</a></li>"$'\n'
                                elif [[ "$in_block" == "$b_name" || "$in_block" == "$l_type" ]]; then
                                    local b_id="${block_id:-$(__slugify "$first_val")}"
                                    local anchor_id="block-${in_block}-${b_id}"
                                    list_html+="<li><a href=\"${t_url}#${anchor_id}\">$first_val</a></li>"$'\n'
                                fi
                                in_block=""
                            else
                                if [[ "$in_block" == "table" ]]; then
                                    t_buffer+=("$t_line")
                                elif [[ "$t_line" =~ ^[[:space:]]*::[[:space:]]*([a-zA-Z0-9_-]+):[[:space:]]*(.*)$ ]]; then
                                    local k="${BASH_REMATCH[1]}" v="${BASH_REMATCH[2]}"
                                    v="${v#"${v%%[![:space:]]*}"}"; v="${v%"${v##*[![:space:]]}"}"
                                    if [[ "$k" == "__id__" ]]; then block_id="$v"; fi
                                    if [[ -z "$first_key" && "$k" != "__id__" ]]; then
                                        first_key="$k"
                                        first_val="$v"
                                    fi
                                fi
                            fi
                        fi
                    done < "$target_file"
                else
                    list_html+="<li><span class=\"wiki-ref-err\">File not found: ${l_path}</span></li>"$'\n'
                fi
            fi
            list_html+="</ul>"
            content="${content//"$full_match"/$list_html}"
        done
    }

    __render_layout() {
        local PAGE_LAYOUT="" skip=0 ll
        for ll in "${layout_lines[@]}"; do
            if [[ "$ll" == *"{%"* ]]; then
                if [[ "$ll" =~ \{\%\ *if\ *\'([^\']+)\'\ *in\ *pagename\ *and\ *not\ *pagename\ *==\ *\"([^\"]+)\"\ *\%\} ]]; then
                    if [[ "$pagename" == *"${BASH_REMATCH[1]}"* && "$pagename" != "${BASH_REMATCH[2]}" ]]; then skip=0; else skip=1; fi
                    continue
                fi
                if [[ "$ll" =~ \{\%\ *if\ *\'([^\']+)\'\ *in\ *pagename\ *\%\} ]]; then
                    if [[ "$pagename" == *"${BASH_REMATCH[1]}"* ]]; then skip=0; else skip=1; fi
                    continue
                fi
                if [[ "$ll" =~ \{\%\ *else\ *\%\} ]]; then
                    if [[ $skip -eq 0 ]]; then skip=1; else skip=0; fi
                    continue
                fi
                if [[ "$ll" =~ \{\%\ *endif\ *\%\} ]]; then
                    skip=0
                    continue
                fi
                if [[ "$ll" =~ \{\%\ *(for|from|include|endfor).*\%\} ]]; then continue; fi
            fi
            if (( skip == 1 )); then continue; fi
            if [[ "$ll" == *"{{ render_menu_item"* || "$ll" == *"{{ item"* ]]; then continue; fi
            if [[ "$ll" == *"{{ page."* ]]; then
                while [[ "$ll" =~ \{\{\ *page\.([a-zA-Z0-9_.-]+)\ *\}\} ]]; do
                    local full_match="${BASH_REMATCH[0]}"
                    local var_name="page.${BASH_REMATCH[1]}"
                    local val="${PAGE_VARS[$var_name]}"
                    ll="${ll//"$full_match"/$val}"
                done
            fi
            if [[ "$ll" == *"{{ wiki.frontmatter."* ]]; then
                while [[ "$ll" =~ \{\{\ *wiki\.frontmatter\.([a-zA-Z0-9_.-]+)\ *\}\} ]]; do
                    local full_match="${BASH_REMATCH[0]}"
                    local var_name="page.${BASH_REMATCH[1]}"
                    local val="${PAGE_VARS[$var_name]}"
                    ll="${ll//"$full_match"/$val}"
                done
            fi
            PAGE_LAYOUT+="$ll"$'\n'
        done
        
        rendered="$PAGE_LAYOUT"
        local search_tags=("{{ body }}" "{{ pagename }}" "{{pagename}}" "{{ wiki.menu }}" "{{wiki.menu}}" "{{ menu }}" "{{menu}}" "{{ wiki.featured }}" "{{wiki.featured}}" "{{ featured }}" "{{featured}}" "{{ year }}" "{{ now }}" "{{ wiki.search }}" "{{wiki.search}}" "{{ wiki.breadcrumb }}" "{{wiki.breadcrumb}}")
        
        local year now t_val=""
        printf -v year "%(%Y)T" -1
        printf -v now "%(%Y/%m/%d at %H:%M)T" -1
        
        local search_js="const SEARCH_CONFIG = ["
        local sf=1
        for k in "${!SEARCH_INDEX_MAP[@]}"; do
            (( sf == 0 )) && search_js+=","
            local fallback="${k^}"
            local tkey="${BLOCK_TITLE_KEYS[$k]:-$k}"
            [[ "$k" == "page" ]] && tkey="pagename"
            [[ "$k" == "table" ]] && tkey="caption"
            search_js+=" { id: '$k', others: ['${k}s'], titleKey: '$tkey', fallback: '$fallback' }"
            sf=0
        done
        search_js+=" ];"
        
        local WIKI_BREADCRUMB_HTML=""
        __partial_breadcrumb
        
        for search in "${search_tags[@]}"; do
            case "$search" in
                "{{ body }}") t_val="$content" ;;
                "{{ pagename }}"|"{{pagename}}") t_val="$title" ;;
                "{{ wiki.menu }}"|"{{wiki.menu}}"|"{{ menu }}"|"{{menu}}") t_val="$WIKI_MENU_HTML" ;;
                "{{ wiki.featured }}"|"{{wiki.featured}}"|"{{ featured }}"|"{{featured}}") t_val="$WIKI_FEATURED_HTML" ;;
                "{{ year }}") t_val="$year" ;;
                "{{ now }}") t_val="$now" ;;
                "{{ wiki.search }}"|"{{wiki.search}}") t_val="$search_js" ;;
                "{{ wiki.breadcrumb }}"|"{{wiki.breadcrumb}}") t_val="$WIKI_BREADCRUMB_HTML" ;;
            esac
            rendered="${rendered//"$search"/$t_val}"
        done
    }

    __render_main() {
        local file="$1" pagename="$2" out_path="$3" current_dir="$4"
        local h_regex='^(#{1,6})\ +(.*)'
        local _amp="&amp;" _lt="&lt;" _gt="&gt;"
        if shopt -q patsub_replacement 2>/dev/null; then _amp="\\&amp;"; _lt="\\&lt;"; _gt="\\&gt;"; fi
        local content="" rendered="" in_frontmatter=0 title="$pagename" TOC_HTML="<ul class=\"toc\">"$'\n'
        local page_table_count=0 page_diagram_count=0
        local in_code_block=0 in_html_pre=0 in_custom_block="" custom_block_indent="" list_depth=0 was_empty=0 ignore_next_empty=0 set_ignore_this_turn=0 line
        local -a table_buffer=() diagram_buffer=() custom_block_buffer=() hide_buffer=() KEYS_STACK=() LIST_INDENTS=() LIST_TYPES=() lines=()
        local -A PAGE_VARS=()
        mapfile -t lines < "$file"
        __parse_main
        __render_listings
        __render_layout
        __search_index
        printf "%s" "$rendered" > "$out_path"
        __log "Rendered -> $out_path" -t success -l wiki
    }

}
