#! /bin/bash

__listings__() {

    __listing_pages() {
        local args="$*"
        local l_root="$current_dir"
        local l_pattern="*"
        local l_page_label="title"
        local l_exclude=""
        local l_depth="0"
        local -A l_globals=()
        local str="$args"
        while [[ "$str" =~ ([a-zA-Z0-9_.-]+)=([^\"\'[:space:]]+|\"([^\"]+)\"|\'([^\']+)\') ]]; do
            local key="${BASH_REMATCH[1]}"
            local val="${BASH_REMATCH[4]:-${BASH_REMATCH[3]:-${BASH_REMATCH[2]}}}"
            if [[ "$key" == "root" ]]; then l_root="$val"
            elif [[ "$key" == "pattern" ]]; then l_pattern="$val"
            elif [[ "$key" == "page_label" ]]; then l_page_label="$val"
            elif [[ "$key" == "exclude" ]]; then l_exclude="$val"
            elif [[ "$key" == "depth" ]]; then l_depth="$val"
            else
                local g_key="${key#globals.}"
                l_globals["$g_key"]="$val"
            fi
            str="${str#*${BASH_REMATCH[0]}}"
        done
        [[ "$l_root" == "." || -z "$l_root" ]] && l_root=""
        local list_html="<list class=\"list-pages\">"$'\n'"<ul class=\"list-pages-ul\">"$'\n'
        local target_dir="$SOURCEDIR"
        if [[ -n "$l_root" ]]; then
            if [[ "$l_root" == /* ]]; then
                target_dir="$SOURCEDIR${l_root}"
            else
                target_dir="$SOURCEDIR/${l_root//./\/}"
            fi
        fi
        if [[ -d "$target_dir" ]]; then
            local f
            local force_globals=0
            [[ "$l_page_label" == globals.* ]] && force_globals=1
            local s_globstar=0
            shopt -q globstar && s_globstar=1 || shopt -s globstar
            local -a matching_slugs=()
            local -A file_disp_names=()
            local -A file_weights=()
            local -A dir_implicit_weights=()
            for f in "$target_dir"/**/$l_pattern; do
                [[ -f "$f" ]] || continue
                local rel_path="${f#$target_dir/}"
                local slashes="${rel_path//[^\/]/}"
                if (( l_depth > 0 && ${#slashes} >= l_depth )); then continue; fi
                local fname="${f##*/}"
                local fname_no_ext="${fname%.*}"
                if [[ "$fname_no_ext" =~ ^([0-9]+)\.(.+)$ ]]; then
                    fname_no_ext="${BASH_REMATCH[2]}"
                fi
                local rel_dir="${rel_path%/*}"
                [[ "$rel_dir" == "$rel_path" ]] && rel_dir=""
                
                if [[ -n "$rel_dir" ]]; then
                    local clean_rel_dir=""
                    local prev_IFS="$IFS"
                    IFS='/'
                    local -a r_parts=($rel_dir)
                    IFS="$prev_IFS"
                    for r_part in "${r_parts[@]}"; do
                        local current_weight="9999999"
                        if [[ "$r_part" =~ ^([0-9]+)\.(.+)$ ]]; then
                            current_weight="${BASH_REMATCH[1]}"
                            r_part="${BASH_REMATCH[2]}"
                        fi
                        if [[ -z "$clean_rel_dir" ]]; then clean_rel_dir="$r_part"
                        else clean_rel_dir="${clean_rel_dir}/${r_part}"; fi
                        
                        local temp_slug_key=""
                        if [[ -n "$l_root" ]]; then temp_slug_key="${l_root//\//.}.${clean_rel_dir//\//.}"; else temp_slug_key="${clean_rel_dir//\//.}"; fi
                        temp_slug_key="${temp_slug_key#.}"
                        
                        if [[ "$current_weight" != "9999999" ]]; then
                            dir_implicit_weights["$temp_slug_key"]="$current_weight"
                        fi
                    done
                    rel_dir="$clean_rel_dir"
                fi
                
                local slug_key=""
                if [[ -n "$l_root" ]]; then
                    slug_key="${l_root//\//.}"
                    [[ -n "$rel_dir" ]] && slug_key+=".${rel_dir//\//.}"
                    slug_key+=".${fname_no_ext}"
                else
                    slug_key="${rel_dir//\//.}"
                    [[ -n "$slug_key" ]] && slug_key+="."
                    slug_key+="${fname_no_ext}"
                fi
                slug_key="${slug_key#.}"
                
                if [[ -n "$l_exclude" ]]; then
                    local exclude_match=0
                    if [[ "$l_exclude" == *"&&"* ]]; then
                        exclude_match=1
                        local old_ifs="$IFS"; IFS="&"; local -a parts=($l_exclude); IFS="$old_ifs"
                        for p in "${parts[@]}"; do
                            p="${p#"${p%%[![:space:]]*}"}"; p="${p%"${p##*[![:space:]]}"}"
                            [[ -z "$p" ]] && continue
                            if [[ "$slug_key" != $p && "$fname" != $p && "${fname%.*}" != $p && "$fname_no_ext" != $p ]]; then
                                exclude_match=0; break
                            fi
                        done
                    else
                        local old_ifs="$IFS"; IFS="|"; local -a parts=($l_exclude); IFS="$old_ifs"
                        for p in "${parts[@]}"; do
                            p="${p#"${p%%[![:space:]]*}"}"; p="${p%"${p##*[![:space:]]}"}"
                            [[ -z "$p" ]] && continue
                            if [[ "$slug_key" == $p || "$fname" == $p || "${fname%.*}" == $p || "$fname_no_ext" == $p ]]; then
                                exclude_match=1; break
                            fi
                        done
                    fi
                    (( exclude_match == 1 )) && continue
                fi
                
                local match=1
                local -A file_globals=()
                if [[ ${#l_globals[@]} -gt 0 || $force_globals -eq 1 ]]; then
                    local in_globals=0 g_line
                    while IFS= read -r g_line || [[ -n "$g_line" ]]; do
                        g_line="${g_line%$'\r'}"
                        if (( in_globals == 0 )); then
                            [[ "$g_line" =~ ^[[:space:]]*\{\{[[:space:]]*block\.globals[[:space:]]*\}\}[[:space:]]*$ ]] && in_globals=1
                        else
                            [[ "$g_line" =~ ^[[:space:]]*\{\{[[:space:]]*block\.end[[:space:]]*\}\}[[:space:]]*$ ]] && break
                            if [[ "$g_line" =~ ^[[:space:]]*::[[:space:]]*([a-zA-Z0-9_-]+):[[:space:]]*(.*)$ ]]; then
                                file_globals["${BASH_REMATCH[1]}"]="${BASH_REMATCH[2]}"
                            fi
                        fi
                    done < "$f"
                    if [[ ${#l_globals[@]} -gt 0 ]]; then
                        local gk actual_v req_str
                        for gk in "${!l_globals[@]}"; do
                            actual_v="${file_globals[$gk]:-}"
                            if [[ -z "$actual_v" ]]; then match=0; break; fi
                            req_str="${l_globals[$gk]}"
                            
                            if [[ "$req_str" == *"&&"* ]]; then
                                local old_ifs="$IFS"; IFS="&"; local -a req_arr=($req_str); IFS="$old_ifs"
                                for req_v in "${req_arr[@]}"; do
                                    req_v="${req_v#"${req_v%%[![:space:]]*}"}"; req_v="${req_v%"${req_v##*[![:space:]]}"}"
                                    [[ -z "$req_v" ]] && continue
                                    if [[ $actual_v != $req_v ]]; then match=0; break; fi
                                done
                            else
                                local old_ifs="$IFS"; IFS="|"; local -a req_arr=($req_str); IFS="$old_ifs"
                                local or_match=0
                                for req_v in "${req_arr[@]}"; do
                                    req_v="${req_v#"${req_v%%[![:space:]]*}"}"; req_v="${req_v%"${req_v##*[![:space:]]}"}"
                                    [[ -z "$req_v" ]] && continue
                                    if [[ $actual_v == $req_v ]]; then or_match=1; break; fi
                                done
                                if (( or_match == 0 )); then match=0; break; fi
                            fi
                            (( match == 0 )) && break
                        done
                    fi
                fi
                if (( match == 1 )); then
                    local disp_name=""
                    if [[ "$l_page_label" == globals.* ]]; then
                        local g_key="${l_page_label#globals.}"
                        disp_name="${file_globals[$g_key]:-}"
                    elif [[ "$l_page_label" == "name" ]]; then
                        disp_name="${fname_no_ext}"
                    elif [[ "$l_page_label" == "weight" ]]; then
                        disp_name="${PAGE_WEIGHTS[$slug_key]:-9999999}"
                    fi
                    [[ -z "$disp_name" ]] && disp_name="${PAGE_TITLES[$slug_key]:-${fname_no_ext}}"
                    local rel_slug=""
                    if [[ -n "$rel_dir" ]]; then rel_slug="${rel_dir}/${fname_no_ext}"; else rel_slug="${fname_no_ext}"; fi
                    matching_slugs+=("$rel_slug")
                    file_disp_names["$rel_slug"]="$disp_name"
                    file_weights["$rel_slug"]="${PAGE_WEIGHTS[$slug_key]:-9999999}"
                fi
            done
            (( s_globstar == 0 )) && shopt -u globstar
            if [[ ${#matching_slugs[@]} -gt 0 ]]; then
                local -a raw_sorted=()
                local rel_slug
                for rel_slug in "${matching_slugs[@]}"; do
                    local prev_IFS="$IFS"
                    IFS='/'
                    local -a parts=($rel_slug)
                    IFS="$prev_IFS"
                    
                    local sort_key=""
                    local cum_path=""
                    local i
                    for (( i=0; i<${#parts[@]}; i++ )); do
                        local part="${parts[$i]}"
                        if [[ -z "$cum_path" ]]; then cum_path="$part"; else cum_path="${cum_path}/${part}"; fi
                        local w type
                        if (( i == ${#parts[@]} - 1 )); then
                            type="1"
                            w="${file_weights[$rel_slug]:-9999999}"
                        else
                            type="0"
                            local dir_slug_key=""
                            if [[ -n "$l_root" ]]; then dir_slug_key="${l_root//\//.}.${cum_path//\//.}"; else dir_slug_key="${cum_path//\//.}"; fi
                            dir_slug_key="${dir_slug_key#.}"
                            w="${dir_implicit_weights[$dir_slug_key]:-9999999}"
                        fi
                        w="0000000${w}"
                        w="${w: -7}"
                        sort_key+="/${type}_${w}_${part}"
                    done
                    raw_sorted+=("${sort_key}|${rel_slug}")
                done
                local -a sorted_slugs=()
                local line
                while IFS= read -r line; do
                    sorted_slugs+=("${line#*|}")
                done < <(printf "%s\n" "${raw_sorted[@]}" | LC_ALL=C sort -t'|' -k1,1)
                local -a current_path=()
                for rel_slug in "${sorted_slugs[@]}"; do
                    local prev_IFS="$IFS"
                    IFS='/'
                    local -a parts=($rel_slug)
                    IFS="$prev_IFS"
                    local page_name="${parts[${#parts[@]}-1]}"
                    local -a dir_parts=("${parts[@]:0:${#parts[@]}-1}")
                    local common_len=0
                    while [[ $common_len -lt ${#current_path[@]} && $common_len -lt ${#dir_parts[@]} && "${current_path[$common_len]}" == "${dir_parts[$common_len]}" ]]; do
                        common_len=$((common_len + 1))
                    done
                    local i
                    for (( i=${#current_path[@]}-1; i>=common_len; i-- )); do
                        list_html+="</ul></li>"$'\n'
                    done
                    local cum_dir=""
                    for (( i=common_len; i<${#dir_parts[@]}; i++ )); do
                        local dir="${dir_parts[$i]}"
                        if [[ -z "$cum_dir" ]]; then cum_dir="$dir"; else cum_dir="${cum_dir}/${dir}"; fi
                        local dir_slug_key=""
                        if [[ -n "$l_root" ]]; then dir_slug_key="${l_root//\//.}.${cum_dir//\//.}"; else dir_slug_key="${cum_dir//\//.}"; fi
                        dir_slug_key="${dir_slug_key#.}"
                        local dir_disp="${PAGE_TITLES[$dir_slug_key]:-$dir}"
                        [[ "$dir_disp" != */ ]] && dir_disp="${dir_disp}/"
                        list_html+="<li class=\"list-pages-dir\">${dir_disp}<ul class=\"list-pages-ul-inner\">"$'\n'
                    done
                    local p_url=""
                    if [[ -n "$l_root" ]]; then
                        p_url="${l_root//./\/}/${rel_slug}.html"
                    else
                        p_url="${rel_slug}.html"
                    fi
                    [[ "$p_url" != /* ]] && p_url="/${p_url}"
                    p_url="${p_url//\/\//\/}"
                    local disp_name="${file_disp_names[$rel_slug]}"
                    list_html+="<li class=\"list-pages-li\"><a href=\"$p_url\">$disp_name</a></li>"$'\n'
                    current_path=("${dir_parts[@]}")
                done
                local i
                for (( i=${#current_path[@]}-1; i>=0; i-- )); do
                    list_html+="</ul></li>"$'\n'
                done
            fi
        fi
        list_html+="</ul>"$'\n'"</list>"
        printf "%s" "$list_html"
    }
    
    __listing_blocks() {
        local b_type="$1"
        shift
        local singular="${b_type%s}"
        local l_root="" l_depth="999" l_page=""
        
        if [[ $# -eq 1 && "$1" != *=* ]]; then
            l_page="$1"
        else
            local str="$*"
            while [[ "$str" =~ ([a-zA-Z0-9_.-]+)=([^\"\'[:space:]]+|\"([^\"]+)\"|\'([^\']+)\') ]]; do
                local key="${BASH_REMATCH[1]}"
                local val="${BASH_REMATCH[4]:-${BASH_REMATCH[3]:-${BASH_REMATCH[2]}}}"
                if [[ "$key" == "root" ]]; then l_root="$val"
                elif [[ "$key" == "depth" ]]; then l_depth="$val"
                elif [[ "$key" == "page" ]]; then l_page="$val"
                fi
                str="${str#*${BASH_REMATCH[0]}}"
            done
        fi

        local list_html="<list class=\"list-block-${singular}\">"$'\n'"<ul class=\"list-block-${singular}-ul\">"$'\n'
        local -a target_files=()

        if [[ -n "$l_page" ]]; then
            local t_file="$SOURCEDIR/${l_page//./\/}"
            [[ "$t_file" != *.md ]] && t_file="${t_file}.md"
            if [[ -f "$t_file" ]]; then target_files+=("$t_file"); fi
        elif [[ -n "$l_root" ]]; then
            local t_dir="$SOURCEDIR/${l_root//./\/}"
            if [[ -d "$t_dir" ]]; then
                while IFS= read -r -d '' f; do
                    local rel="${f#$t_dir/}"
                    local d_count="${rel//[^\/]/}"
                    if (( ${#d_count} < l_depth )); then
                        target_files+=("$f")
                    fi
                done < <(find "$t_dir" -type f -name "*.md" -print0)
            fi
        else
            target_files+=("$file")
        fi

        local t_f
        for t_f in "${target_files[@]}"; do
            local t_rel="${t_f#$SOURCEDIR/}"
            local t_url="/${t_rel%.md}.html"
            local in_block="" block_id="" first_key="" first_val=""
            local b_context="" b_entity=""
            local item_count_table=0 item_count_diagram=0
            local -a t_buffer=()
            while IFS= read -r t_line || [[ -n "$t_line" ]]; do
                t_line="${t_line%$'\r'}"
                if [[ -z "$in_block" ]]; then
                    if [[ "$t_line" =~ ^[[:space:]]*\{\{[[:space:]]*block\.([a-zA-Z0-9_-]+)[[:space:]]*\}\}[[:space:]]*$ ]]; then
                        local match_type="${BASH_REMATCH[1]}"
                        if [[ "$match_type" == "table" ]]; then ((item_count_table++)); fi
                        if [[ "$match_type" == "diagram" ]]; then ((item_count_diagram++)); fi
                        
                        if [[ "$match_type" == "$b_type" || "$match_type" == "$singular" || "${match_type}s" == "$b_type" ]]; then
                            in_block="$match_type"
                            block_id="" first_key="" first_val=""
                            b_context="" b_entity=""
                            if [[ "$in_block" == "table" ]]; then t_buffer=(); fi
                        fi
                    fi
                else
                    if [[ "$t_line" =~ ^[[:space:]]*\{\{[[:space:]]*block\.end[[:space:]]*\}\}[[:space:]]*$ ]]; then
                        if [[ "$in_block" == "table" ]]; then
                            local caption="" sep_count=0 i
                            for ((i=0; i<${#t_buffer[@]}; i++)); do
                                if [[ "${t_buffer[$i]}" =~ ^[-=_]{4,} ]]; then ((sep_count++)); fi
                            done
                            if [[ $sep_count -ge 2 ]]; then
                                local found_sep=0
                                for ((i=0; i<${#t_buffer[@]}; i++)); do
                                    if [[ "${t_buffer[$i]}" =~ ^[-=_]{4,} ]]; then ((found_sep++)); continue; fi
                                    if [[ $found_sep -eq $sep_count ]]; then
                                        local cl="${t_buffer[$i]}"
                                        cl="${cl#"${cl%%[![:space:]]*}"}"; cl="${cl%"${cl##*[![:space:]]}"}"
                                        if [[ -n "$cl" ]]; then caption="$cl"; break; fi
                                    fi
                                done
                            fi
                            list_html+="<li class=\"list-block-${singular}-li\"><a href=\"${t_url}#table-${item_count_table}\">${caption:-Table ${item_count_table}}</a></li>"$'\n'
                        elif [[ "$in_block" == "diagram" ]]; then
                            list_html+="<li class=\"list-block-${singular}-li\"><a href=\"${t_url}#diagram-${item_count_diagram}\">Diagram ${item_count_diagram}</a></li>"$'\n'
                        else
                            local disp_val="${b_entity:-${b_context:+"${b_context} - "}${first_val}}"
                            local raw_id="${block_id:-${b_entity:-$first_val}}"
                            local clean_id="$(__slugify "$raw_id")"
                            local ref_key="$clean_id"
                            if [[ -n "$b_context" && "$raw_id" != *.* ]]; then
                                ref_key="$(__slugify "${b_context}.${raw_id}")"
                            fi
                            local anchor_id_slug="${ref_key//./-}"
                            local anchor_id="block-${in_block}-${anchor_id_slug}"
                            list_html+="<li class=\"list-block-${singular}-li\"><a href=\"${t_url}#${anchor_id}\">${disp_val:-$anchor_id}</a></li>"$'\n'
                        fi
                        in_block=""
                    else
                        if [[ "$in_block" == "table" ]]; then
                            t_buffer+=("$t_line")
                        elif [[ "$t_line" =~ ^[[:space:]]*::[[:space:]]*([a-zA-Z0-9_-]+):[[:space:]]*(.*)$ ]]; then
                            local k="${BASH_REMATCH[1]}" v="${BASH_REMATCH[2]}"
                            v="${v#"${v%%[![:space:]]*}"}"; v="${v%"${v##*[![:space:]]}"}"
                            if [[ "$k" == "__id__" ]]; then block_id="$v"; fi
                            if [[ "$k" == "__context__" || "$k" == "context" ]]; then b_context="$v"; fi
                            if [[ "$k" == "__entity__" || "$k" == "__entry__" ]]; then b_entity="$v"; fi
                            if [[ -z "$first_key" && "$k" != "__id__" && "$k" != "__context__" && "$k" != "context" && "$k" != "__entry__" && "$k" != "__entity__" ]]; then
                                first_key="$k"; first_val="$v"
                            fi
                        fi
                    fi
                fi
            done < "$t_f"
        done

        list_html+="</ul>"$'\n'"</list>"
        printf "%s" "$list_html"
    }
    
}
