#! /bin/bash

__render__() {
        
    __render_template() {
        local PAGE_LAYOUT="" skip=0 ll
        for ll in "${layout_lines[@]}"; do
            if [[ "$ll" == *"{%"* ]]; then
                if [[ "$ll" =~ \{\%\ *if\ *\'([^\']+)\'\ *in\ *page\.name\ *and\ *not\ *page\.name\ *==\ *\"([^\"]+)\"\ *\%\} ]]; then
                    if [[ "$pagename" == *"${BASH_REMATCH[1]}"* && "$pagename" != "${BASH_REMATCH[2]}" ]]; then skip=0; else skip=1; fi
                    continue
                fi
                if [[ "$ll" =~ \{\%\ *if\ *\'([^\']+)\'\ *in\ *page\.name\ *\%\} ]]; then
                    if [[ "$pagename" == *"${BASH_REMATCH[1]}"* ]]; then skip=0; else skip=1; fi
                    continue
                fi
                if [[ "$ll" =~ \{\%\ *else\ *\%\} ]]; then
                    if [[ $skip -eq 0 ]]; then skip=1; else skip=0; fi
                    continue
                fi
                if [[ "$ll" =~ \{\%\ *endif\ *\%\} ]]; then
                    skip=0
                    continue
                fi
                if [[ "$ll" =~ \{\%\ *(for|from|include|endfor).*\%\} ]]; then continue; fi
            fi
            if (( skip == 1 )); then continue; fi
            if [[ "$ll" == *"{{ render_menu_item"* || "$ll" == *"{{ item"* ]]; then continue; fi
            if [[ "$ll" == *"{{ page."* ]]; then
                while [[ "$ll" =~ \{\{\ *page\.([a-zA-Z0-9_.-]+)\ *\}\} ]]; do
                    local full_match="${BASH_REMATCH[0]}"
                    local suffix="${BASH_REMATCH[1]}"
                    if [[ "$suffix" == "name" || "$suffix" == "body" || "$suffix" == "title" ]]; then
                        ll="${ll/"$full_match"/%%RETAIN_PAGE_${suffix}%%}"
                    else
                        local var_name="page.${suffix}"
                        local val="${PAGE_VARS[$var_name]}"
                        ll="${ll//"$full_match"/$val}"
                    fi
                done
                local pnt="{{ page.name }}"
                local pbt="{{ page.body }}"
                local ptt="{{ page.title }}"
                ll="${ll//%%RETAIN_PAGE_name%%/$pnt}"
                ll="${ll//%%RETAIN_PAGE_body%%/$pbt}"
                ll="${ll//%%RETAIN_PAGE_title%%/$ptt}"
            fi
            if [[ "$ll" == *"{{ wiki.frontmatter."* ]]; then
                while [[ "$ll" =~ \{\{\ *wiki\.frontmatter\.([a-zA-Z0-9_.-]+)\ *\}\} ]]; do
                    local full_match="${BASH_REMATCH[0]}"
                    local var_name="page.${BASH_REMATCH[1]}"
                    local val="${PAGE_VARS[$var_name]}"
                    ll="${ll//"$full_match"/$val}"
                done
            fi
            PAGE_LAYOUT+="$ll"$'\n'
        done
        local p_breadcrumb=1 p_featured=1 p_menu=1
        local p_str="${PAGE_VARS["page.partials"]:-}"
        if [[ -n "$p_str" ]]; then
            while [[ "$p_str" =~ ([a-zA-Z0-9_-]+)=([a-zA-Z0-9_-]+) ]]; do
                local k="${BASH_REMATCH[1]}" v="${BASH_REMATCH[2]}"
                if [[ "$v" == "false" || "$v" == "0" ]]; then
                    [[ "$k" == "breadcrumb" ]] && p_breadcrumb=0
                    [[ "$k" == "featured" ]] && p_featured=0
                    [[ "$k" == "menu" ]] && p_menu=0
                elif [[ "$v" == "true" || "$v" == "1" ]]; then
                    [[ "$k" == "breadcrumb" ]] && p_breadcrumb=1
                    [[ "$k" == "featured" ]] && p_featured=1
                    [[ "$k" == "menu" ]] && p_menu=1
                fi
                p_str="${p_str#*${BASH_REMATCH[0]}}"
            done
        fi
        rendered="$PAGE_LAYOUT"
        while [[ "$rendered" =~ \{\{[[:space:]]*(wiki\.)?menu[[:space:]]+([^}]+)\}\} ]]; do
            local full_match="${BASH_REMATCH[0]}"
            local args="${BASH_REMATCH[2]}"
            local custom_menu=""
            if (( p_menu == 1 )); then
                custom_menu="$(__partial_menu $args)"
            fi
            rendered="${rendered/"$full_match"/$custom_menu}"
        done
        while [[ "$rendered" =~ \{\{[[:space:]]*(wiki\.)?breadcrumb[[:space:]]*([^}]*)\}\} ]]; do
            local full_match="${BASH_REMATCH[0]}"
            local args="${BASH_REMATCH[2]}"
            local custom_bc=""
            if (( p_breadcrumb == 1 )); then
                custom_bc="$(__partial_breadcrumb $args)"
            fi
            rendered="${rendered/"$full_match"/$custom_bc}"
        done
        while [[ "$rendered" =~ \{\{[[:space:]]*(wiki\.)?related([[:space:]]+([^}]+))?[[:space:]]*\}\} ]]; do
            local full_match="${BASH_REMATCH[0]}"
            local args="${BASH_REMATCH[3]:-}"
            local custom_related="$(__partial_related $args)"
            rendered="${rendered/"$full_match"/$custom_related}"
        done
        while [[ "$rendered" =~ \{\{[[:space:]]*(wiki\.)?head[[:space:]]+([^}]+)\}\} ]]; do
            local full_match="${BASH_REMATCH[0]}"
            local args="${BASH_REMATCH[2]}"
            local custom_head="$(__partial_head $args)"
            rendered="${rendered/"$full_match"/$custom_head}"
        done
        local search_tags=("{{ page.body }}" "{{page.body}}" "{{ page.name }}" "{{page.name}}" "{{ page.title }}" "{{page.title}}" "{{ wiki.menu }}" "{{wiki.menu}}" "{{ menu }}" "{{menu}}" "{{ wiki.featured }}" "{{wiki.featured}}" "{{ datetime.year }}" "{{datetime.year}}" "{{ datetime.now }}" "{{datetime.now}}" "{{ wiki.search }}" "{{wiki.search}}" "{{ wiki.search_page }}" "{{wiki.search_page}}" "{{ wiki.thumb }}" "{{wiki.thumb}}" "{{ wiki.tags }}" "{{wiki.tags}}")
        local year now t_val=""
        printf -v year "%(%Y)T" -1
        printf -v now "%(%Y/%m/%d at %H:%M)T" -1
        local WIKI_SEARCH_HTML="" WIKI_SEARCH_PAGE_HTML="" WIKI_THUMB_HTML="" WIKI_TAGS_HTML=""
        __partial_search
        __partial_search_page
        __partial_thumb
        __partial_tags
        for search in "${search_tags[@]}"; do
            case "$search" in
                "{{ page.body }}"|"{{page.body}}") t_val="$content" ;;
                "{{ page.name }}"|"{{page.name}}") t_val="$title" ;;
                "{{ page.title }}"|"{{page.title}}") t_val="${PAGE_TITLES[$pagename]:-$pagename}" ;;
                "{{ wiki.menu }}"|"{{wiki.menu}}"|"{{ menu }}"|"{{menu}}")
                    if (( p_menu == 1 )); then t_val="$WIKI_MENU_HTML"; else t_val=""; fi ;;
                "{{ wiki.featured }}"|"{{wiki.featured}}"|"{{ featured }}"|"{{featured}}")
                    if (( p_featured == 1 )); then t_val="$WIKI_FEATURED_HTML"; else t_val=""; fi ;;
                "{{ datetime.year }}"|"{{datetime.year}}") t_val="$year" ;;
                "{{ datetime.now }}"|"{{datetime.now}}") t_val="$now" ;;
                "{{ wiki.search }}"|"{{wiki.search}}") t_val="$WIKI_SEARCH_HTML" ;;
                "{{ wiki.search_page }}"|"{{wiki.search_page}}") t_val="$WIKI_SEARCH_PAGE_HTML" ;;
                "{{ wiki.thumb }}"|"{{wiki.thumb}}") t_val="$WIKI_THUMB_HTML" ;;
                "{{ wiki.tags }}"|"{{wiki.tags}}") t_val="$WIKI_TAGS_HTML" ;;
            esac
            rendered="${rendered//"$search"/$t_val}"
        done
        local auto_js="<script>%%WIKI_SEARCH_CONFIG%%; if (typeof hljs !== 'undefined') hljs.highlightAll();</script>"
        if [[ "$rendered" == *"</body>"* ]]; then
            rendered="${rendered/<\/body>/$auto_js$'\n'<\/body>}"
        else
            rendered+="$auto_js"$'\n'
        fi
    }

    __render_main() {
        local file="$1" pagename="$2" out_path="$3" current_dir="$4"
        local h_regex='^(#{1,6})\ +(.*)'
        local _amp="&amp;" _lt="&lt;" _gt="&gt;"
        if shopt -q patsub_replacement 2>/dev/null; then _amp="\\&amp;"; _lt="\\&lt;"; _gt="\\&gt;"; fi
        local content="" rendered="" in_frontmatter=0 title="$pagename" TOC_HTML="<ul class=\"toc\">"$'\n'
        local page_table_count=0 page_diagram_count=0
        local in_code_block=0 in_html_pre=0 in_custom_block="" custom_block_indent="" list_depth=0 was_empty=0 ignore_next_empty=0 set_ignore_this_turn=0 line
        local -a table_buffer=() diagram_buffer=() custom_block_buffer=() hide_buffer=() KEYS_STACK=() LIST_INDENTS=() LIST_TYPES=() lines=()
        local -A PAGE_VARS=()
        mapfile -t lines < "$file"
        
        __parse_main
        
        TOC_HTML+="</ul>"
        content="${content//\{\{TOC_PLACEHOLDER\}\}/$TOC_HTML}"
        
        local ref_re='%%WIKI_REF:([^:]+):([^:]+):([^%]+)%%'
        local new_content=""
        local rem="$content"
        while [[ "$rem" =~ $ref_re ]]; do
            local full="${BASH_REMATCH[0]}"
            local topic="${BASH_REMATCH[1]}"
            local ref_key="${BASH_REMATCH[2]}"
            local label="${BASH_REMATCH[3]}"
            local key="${topic}::${ref_key}"
            local target="${WIKI_REFS[$key]:-}"
            
            if [[ -z "$target" && -n "$w_name" ]]; then
                target="${WIKI_REFS[${w_name}::${ENV:-}::${key}]:-}"
            fi
            
            if [[ -z "$target" ]]; then
                local clean_key="${key//[^a-zA-Z0-9_.:-]/}"
                local k
                for k in "${!WIKI_REFS[@]}"; do
                    local clean_k="${k//[^a-zA-Z0-9_.:-]/}"
                    if [[ "$clean_k" == "$clean_key" || "$clean_k" == *"::${clean_key}" ]]; then
                        target="${WIKI_REFS[$k]}"
                        break
                    fi
                done
            fi
            
            local replacement=""
            if [[ -z "$target" ]]; then
                replacement="<span class=\"wiki-ref-err\">${label}</span>"
            else
                local href=""
                if [[ "$target" == http://* || "$target" == https://* ]]; then 
                    href="$target"
                else
                    local internal_path="${target%:*}" marker="${target##*:}"
                    [[ "$target" != *":"* ]] && marker=""
                    internal_path="${internal_path//./\/}"; href="/${internal_path}.html"
                    [[ -n "$marker" ]] && href="${href}#${marker}"
                fi
                replacement="<a class=\"wiki-topic-${topic}\" href=\"${href}\">${label}</a>"
            fi
            
            local pre="${rem%%"$full"*}"
            new_content+="${pre}${replacement}"
            rem="${rem#*"$full"}"
        done
        new_content+="$rem"
        content="$new_content"
        
        __search_index
        __render_template
        
        printf "%s" "$rendered" > "$out_path"
        __log "Rendered -> $out_path" -t success -l wiki
    }    

}
