#! /bin/bash

__web__() {
    __declare --dict ENV_WEB_BROWSERS ENV_WEB_MARKS ENV_WEB_PROTOCOLS ENV_WEB_ENGINES

    __web_update_entry() {
        local dict="$1" env="$2" key="$3" val="$4" mode="$5"
        local current=""
        
        [[ "$dict" == "browsers" ]]  && current="${ENV_WEB_BROWSERS[$env]:-}"
        [[ "$dict" == "marks" ]]     && current="${ENV_WEB_MARKS[$env]:-}"
        [[ "$dict" == "protocols" ]] && current="${ENV_WEB_PROTOCOLS[$env]:-}"
        [[ "$dict" == "engines" ]]   && current="${ENV_WEB_ENGINES[$env]:-}"
        
        local new_val=","
        local IFS=','
        for entry in $current; do
            if [[ -n "$entry" ]]; then
                if [[ "$mode" == "list_add" || "$mode" == "list_rm" ]]; then
                    [[ "$entry" != "$key" ]] && new_val+="${entry},"
                else
                    [[ "$entry" != "${key}:"* ]] && new_val+="${entry},"
                fi
            fi
        done
        new_val="${new_val#,}"
        
        if [[ "$mode" == "set" && -n "$val" ]]; then
            new_val+="${key}:${val},"
        elif [[ "$mode" == "list_add" ]]; then
            new_val+="${key},"
        fi
        
        [[ "$dict" == "browsers" ]]  && __update "ENV_WEB_BROWSERS" "$env" "$new_val" "set"
        [[ "$dict" == "marks" ]]     && __update "ENV_WEB_MARKS" "$env" "$new_val" "set"
        [[ "$dict" == "protocols" ]] && __update "ENV_WEB_PROTOCOLS" "$env" "$new_val" "set"
        [[ "$dict" == "engines" ]]   && __update "ENV_WEB_ENGINES" "$env" "$new_val" "set"
    }

    __web__.browsers() {
        local cmd="$1"; shift
        case "$cmd" in
            set)
                local browser="$1"; shift
                local cmd_str="" priv_str="" t_env="$ENV"
                while [[ $# -gt 0 ]]; do
                    case "$1" in
                        -c|--command) cmd_str="$2"; shift ;;
                        --command=*)  cmd_str="${1#*=}" ;;
                        -p|--private) priv_str="$2"; shift ;;
                        --private=*)  priv_str="${1#*=}" ;;
                        -e|--env)     t_env="$2"; shift ;;
                        --env=*)      t_env="${1#*=}" ;;
                    esac
                    shift
                done
                [[ -z "$browser" || -z "$t_env" ]] && return 1
                __web_update_entry "browsers" "$t_env" "$browser" "${cmd_str}@@${priv_str}" "set"
                ;;
            ls|la)
                local t_env="$ENV" is_all=0
                [[ "$cmd" == "la" ]] && is_all=1
                while [[ $# -gt 0 ]]; do
                    case "$1" in
                        -e|--env) t_env="$2"; shift ;;
                        -a|--all) is_all=1 ;;
                    esac
                    shift
                done
                if (( is_all )); then
                    for e in "${!ENV_WEB_BROWSERS[@]}"; do echo "[$e]: ${ENV_WEB_BROWSERS[$e]//,/ }"; done
                else
                    echo "${ENV_WEB_BROWSERS[$t_env]//,/ }"
                fi
                ;;
            rm)
                local browser="$1"; shift
                local t_env="$ENV"
                while [[ $# -gt 0 ]]; do case "$1" in -e|--env) t_env="$2"; shift;; esac; shift; done
                __web_update_entry "browsers" "$t_env" "$browser" "" "rm"
                ;;
            prune)
                local t_env="$ENV"
                while [[ $# -gt 0 ]]; do case "$1" in -e|--env) t_env="$2"; shift;; esac; shift; done
                __update "ENV_WEB_BROWSERS" "$t_env" "" "rm"
                ;;
        esac
    }

    __web__.marks() {
        local cmd="$1"; shift
        case "$cmd" in
            set)
                local name="" url="" browser="" t_env="$ENV"
                local pos_args=()
                while [[ $# -gt 0 ]]; do
                    case "$1" in
                        -u|--url)     url="$2"; shift ;;
                        --url=*)      url="${1#*=}" ;;
                        -e|--env)     t_env="$2"; shift ;;
                        --env=*)      t_env="${1#*=}" ;;
                        -b|--browser) browser="$2"; shift ;;
                        --browser=*)  browser="${1#*=}" ;;
                        *)            pos_args+=("$1") ;;
                    esac
                    shift
                done
                
                if [[ -z "$url" && ${#pos_args[@]} -gt 1 ]]; then
                    url="${pos_args[-1]}"
                    unset 'pos_args[${#pos_args[@]}-1]'
                fi
                
                for p in "${pos_args[@]}"; do
                    if [[ -z "$name" ]]; then name="$p"
                    else name="${name}.${p}"
                    fi
                done

                [[ -z "$name" || -z "$url" || -z "$t_env" ]] && return 1
                __web_update_entry "marks" "$t_env" "$name" "${url}@@${browser}" "set"
                ;;
            ls)
                local t_env="$ENV"
                while [[ $# -gt 0 ]]; do case "$1" in -e|--env) t_env="$2"; shift;; esac; shift; done
                echo "${ENV_WEB_MARKS[$t_env]//,/ }"
                ;;
            rm)
                local name="" t_env="$ENV"
                while [[ $# -gt 0 ]]; do
                    case "$1" in
                        -e|--env) t_env="$2"; shift ;;
                        --env=*)  t_env="${1#*=}" ;;
                        *)
                            if [[ -z "$name" ]]; then name="$1"
                            else name="${name}.$1"
                            fi
                            ;;
                    esac
                    shift
                done
                [[ -z "$name" ]] && return 1
                __web_update_entry "marks" "$t_env" "$name" "" "rm"
                ;;
        esac
    }

    __web__.protocols() {
        local cmd="$1"; shift
        case "$cmd" in
            allow)
                local proto="$1"; shift
                local t_env="$ENV"
                while [[ $# -gt 0 ]]; do case "$1" in -e|--env) t_env="$2"; shift;; esac; shift; done
                __web_update_entry "protocols" "$t_env" "$proto" "" "list_add"
                ;;
            deny)
                local proto="$1"; shift
                local t_env="$ENV"
                while [[ $# -gt 0 ]]; do case "$1" in -e|--env) t_env="$2"; shift;; esac; shift; done
                __web_update_entry "protocols" "$t_env" "$proto" "" "list_rm"
                ;;
        esac
    }

    __web__.engines() {
        local cmd="$1"; shift
        case "$cmd" in
            set)
                local engine="$1"; shift
                local url="" t_env="$ENV"
                while [[ $# -gt 0 ]]; do
                    case "$1" in
                        -u|--url) url="$2"; shift ;;
                        -e|--env) t_env="$2"; shift ;;
                    esac
                    shift
                done
                __web_update_entry "engines" "$t_env" "$engine" "$url" "set"
                ;;
            ls|la)
                local t_env="$ENV" is_all=0
                [[ "$cmd" == "la" ]] && is_all=1
                while [[ $# -gt 0 ]]; do case "$1" in -e|--env) t_env="$2"; shift;; -a|--all) is_all=1;; esac; shift; done
                if (( is_all )); then
                    for e in "${!ENV_WEB_ENGINES[@]}"; do echo "[$e]: ${ENV_WEB_ENGINES[$e]//,/ }"; done
                else
                    echo "${ENV_WEB_ENGINES[$t_env]//,/ }"
                fi
                ;;
            rm)
                local engine="$1"; shift
                local t_env="$ENV"
                while [[ $# -gt 0 ]]; do case "$1" in -e|--env) t_env="$2"; shift;; esac; shift; done
                __web_update_entry "engines" "$t_env" "$engine" "" "rm"
                ;;
        esac
    }

    __web_get_browser_cmd() {
        local b_name="$1" t_env="$2"
        local b_data=",${ENV_WEB_BROWSERS[$t_env]:-}"
        b_data="${b_data##*,${b_name}:}"
        echo "${b_data%%,*}"
    }

    __web__.open() {
        local mark="" browser="" t_env="$ENV"
        while [[ $# -gt 0 ]]; do
            case "$1" in
                -b|--browser) browser="$2"; shift ;;
                --browser=*)  browser="${1#*=}" ;;
                -e|--env)     t_env="$2"; shift ;;
                --env=*)      t_env="${1#*=}" ;;
                *)
                    if [[ -z "$mark" ]]; then mark="$1"
                    else mark="${mark}.$1"
                    fi
                    ;;
            esac
            shift
        done

        local m_data=",${ENV_WEB_MARKS[$t_env]:-}"
        m_data="${m_data##*,${mark}:}"
        m_data="${m_data%%,*}"
        
        local url="${m_data%%@@*}"
        local m_browser="${m_data##*@@}"

        [[ -z "$url" || "$url" == ",${ENV_WEB_MARKS[$t_env]:-}" ]] && return 1

        local proto="${url%%://*}"
        local allowed=",${ENV_WEB_PROTOCOLS[$t_env]:-http,https},"
        [[ "$allowed" != *",${proto},"* ]] && return 1

        local b_target="${browser:-${m_browser:-$BROWSER}}"
        local b_cmd_data="$(__web_get_browser_cmd "$b_target" "$t_env")"
        local b_cmd="${b_cmd_data%%@@*}"
        
        [[ -z "$b_cmd" ]] && b_cmd="$b_target"
        [[ -z "$b_cmd" ]] && b_cmd="xdg-open"

        ( $b_cmd "$url" >/dev/null 2>&1 & )
    }

    __web__.search() {
        local engine="" browser="" t_env="$ENV" terms=""
        while [[ $# -gt 0 ]]; do
            case "$1" in
                -s|--engine)  engine="$2"; shift ;;
                -b|--browser) browser="$2"; shift ;;
                -e|--env)     t_env="$2"; shift ;;
                *)            
                    local t="${1// /+}"
                    terms="${terms}${terms:++}${t}" 
                    ;;
            esac
            shift
        done

        engine="${engine:-$ENGINE}"
        local e_data=",${ENV_WEB_ENGINES[$t_env]:-}"
        e_data="${e_data##*,${engine}:}"
        e_data="${e_data%%,*}"
        [[ -z "$e_data" || "$e_data" == ",${ENV_WEB_ENGINES[$t_env]:-}" ]] && return 1

        local url="${e_data//.../$terms}"

        local b_target="${browser:-$BROWSER}"
        local b_cmd_data="$(__web_get_browser_cmd "$b_target" "$t_env")"
        local b_cmd="${b_cmd_data%%@@*}"
        
        [[ -z "$b_cmd" ]] && b_cmd="$b_target"
        [[ -z "$b_cmd" ]] && b_cmd="xdg-open"

        ( $b_cmd "$url" >/dev/null 2>&1 & )
    }

    web.__help__() {
        echo """ABOUT:
    omni web bookmarks and search manager

USAGE:
    web <command> [args]

COMMANDS:
    browsers  set <browser> [-c <cmd>] [-p <priv_cmd>] [-e <env>]
              ls|la [-e <env>]
              rm <browser> [-e <env>]
              prune [-e <env>]
    marks     set <name> [<url>] [-u <url>] [-b <browser>] [-e <env>]
              ls [-e <env>]
              rm <name> [-e <env>]
    protocols allow|deny <protocol> [-e <env>]
    engines   set <engine> [-u <url>] [-e <env>]
              ls|la [-e <env>]
              rm <engine> [-e <env>]
    open      <mark> [-b <browser>] [-e <env>]
    search    <terms> [-s <engine>] [-b <browser>] [-e <env>]

ALIASES:
    w  <mark>             -> web open <mark>
    wa <name> <url>       -> web marks set <name> <url>
    wd <name>             -> web marks rm <name>
    ws <terms> -s <engine> -> web search <terms> -s <engine>""" >&2
    }

    web() {
        local cmd="$1"
        [[ -z "$cmd" || "$cmd" == "--help" || "$cmd" == "-h" ]] && { web.__help__; return 0; }
        shift
        case "$cmd" in
            browsers)  __web__.browsers "$@" ;;
            marks)     __web__.marks "$@" ;;
            protocols) __web__.protocols "$@" ;;
            engines)   __web__.engines "$@" ;;
            open)      __web__.open "$@" ;;
            search)    __web__.search "$@" ;;
            *)         return 1 ;;
        esac
    }

    web.__compl__() {
        local cur="${COMP_WORDS[COMP_CWORD]}" prev="${COMP_WORDS[COMP_CWORD-1]}"
        local cmd0="${COMP_WORDS[0]}"
        COMPREPLY=()

        local base_cmd="${COMP_WORDS[1]:-}"
        local sub_cmd="${COMP_WORDS[2]:-}"
        local target_cword=$COMP_CWORD

        if [[ "$cmd0" == "w" ]]; then
            base_cmd="open"
            ((target_cword+=1))
        elif [[ "$cmd0" == "wa" ]]; then
            base_cmd="marks"
            sub_cmd="set"
            ((target_cword+=2))
        elif [[ "$cmd0" == "wd" ]]; then
            base_cmd="marks"
            sub_cmd="rm"
            ((target_cword+=2))
        elif [[ "$cmd0" == "ws" ]]; then
            base_cmd="search"
            ((target_cword+=1))
        fi

        _get_keys() {
            local dict="$1" e="$2"
            local current=""
            [[ "$dict" == "browsers" ]]  && current="${ENV_WEB_BROWSERS[$e]:-}"
            [[ "$dict" == "marks" ]]     && current="${ENV_WEB_MARKS[$e]:-}"
            [[ "$dict" == "protocols" ]] && current="${ENV_WEB_PROTOCOLS[$e]:-}"
            [[ "$dict" == "engines" ]]   && current="${ENV_WEB_ENGINES[$e]:-}"
            
            local k="" IFS=','
            for entry in $current; do
                [[ -n "$entry" ]] && k+="${entry%%:*} "
            done
            echo "$k"
        }

        _complete_marks() {
            local target_start="$1"
            local prefix=""
            for ((i=target_start; i<COMP_CWORD; i++)); do
                local w="${COMP_WORDS[i]}"
                if [[ "$w" == -* || "${COMP_WORDS[i-1]}" == "-b" || "${COMP_WORDS[i-1]}" == "--browser" || "${COMP_WORDS[i-1]}" == "-e" || "${COMP_WORDS[i-1]}" == "--env" ]]; then
                    continue
                fi
                if [[ -z "$prefix" ]]; then prefix="$w"
                else prefix="${prefix}.${w}"
                fi
            done

            local current="${ENV_WEB_MARKS[$ENV]:-}"
            local keys=()
            local IFS=','
            for entry in $current; do
                [[ -n "$entry" ]] && keys+=("${entry%%:*}")
            done
            local IFS=$' \t\n'

            local search_prefix=""
            [[ -n "$prefix" ]] && search_prefix="${prefix}."
            local actual_prefix="$search_prefix"
            local user_input="$cur"
            
            if [[ "$user_input" == *.* ]]; then
                actual_prefix="${search_prefix}${user_input%.*}."
                user_input="${user_input##*.}"
            fi

            local suggestions=()
            for k in "${keys[@]}"; do
                if [[ -z "$actual_prefix" ]]; then
                    if [[ "$k" == *.* ]]; then
                        suggestions+=("${k%%.*}")
                    else
                        suggestions+=("$k")
                    fi
                else
                    if [[ "$k" == "${actual_prefix}"* ]]; then
                        local rem="${k#$actual_prefix}"
                        if [[ "$rem" == *.* ]]; then
                            suggestions+=("${rem%%.*}")
                        else
                            suggestions+=("$rem")
                        fi
                    fi
                fi
            done

            if [[ ${#suggestions[@]} -gt 0 ]]; then
                local opts=$(printf "%s\n" "${suggestions[@]}" | sort -u)
                local matches=( $(compgen -W "$opts" -- "$user_input") )
                
                local append_prefix=""
                [[ "$cur" == *.* ]] && append_prefix="${cur%.*}."
                for m in "${matches[@]}"; do
                    COMPREPLY+=("${append_prefix}${m}")
                done

                if [[ ${#COMPREPLY[@]} -eq 1 ]]; then
                    local full_ns="${search_prefix}${COMPREPLY[0]}"
                    for k in "${keys[@]}"; do
                        if [[ "$k" == "${full_ns}."* ]]; then
                            compopt -o nospace 2>/dev/null
                            break
                        fi
                    done
                fi
            fi
        }

        if [[ "$prev" == "-e" || "$prev" == "--env" ]]; then
            COMPREPLY=( $(compgen -W "${!ENVS[*]}" -- "$cur") )
            return 0
        fi

        if [[ "$cmd0" == "web" && "$target_cword" == 1 ]]; then
            local top_lvl="browsers marks protocols engines open search --help"
            local current="${ENV_WEB_MARKS[$ENV]:-}"
            local top_marks=""
            local IFS=','
            for entry in $current; do
                if [[ -n "$entry" ]]; then
                    local k="${entry%%:*}"
                    if [[ "$k" == *.* ]]; then top_marks+="${k%%.*} "
                    else top_marks+="${k} "
                    fi
                fi
            done
            local IFS=$' \t\n'
            
            local opts=$(printf "%s\n" $top_lvl $top_marks | sort -u)
            COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
            
            if [[ ${#COMPREPLY[@]} -eq 1 ]]; then
                local m="${COMPREPLY[0]}"
                if [[ " $top_lvl " != *" $m "* ]]; then
                    local IFS=','
                    for entry in $current; do
                        local k="${entry%%:*}"
                        if [[ "$k" == "${m}."* ]]; then
                            compopt -o nospace 2>/dev/null
                            break
                        fi
                    done
                    local IFS=$' \t\n'
                fi
            fi
            return 0
        fi

        case "$base_cmd" in
            browsers)
                if [[ "$target_cword" == 2 ]]; then
                    COMPREPLY=( $(compgen -W "set ls rm prune" -- "$cur") )
                    return 0
                fi
                if [[ "$sub_cmd" == "set" ]]; then
                    COMPREPLY=( $(compgen -W "--command --private --env $(_get_keys browsers "$ENV")" -- "$cur") )
                elif [[ "$sub_cmd" == "ls" ]]; then
                    COMPREPLY=( $(compgen -W "--env --all" -- "$cur") )
                elif [[ "$sub_cmd" == "rm" ]]; then
                    COMPREPLY=( $(compgen -W "--env $(_get_keys browsers "$ENV")" -- "$cur") )
                elif [[ "$sub_cmd" == "prune" ]]; then
                    COMPREPLY=( $(compgen -W "--env" -- "$cur") )
                fi
                ;;
            marks)
                if [[ "$target_cword" == 2 ]]; then
                    COMPREPLY=( $(compgen -W "set ls rm" -- "$cur") )
                    return 0
                fi
                if [[ "$sub_cmd" == "set" ]]; then
                    if [[ "$prev" == "-b" || "$prev" == "--browser" ]]; then
                        COMPREPLY=( $(compgen -W "$(_get_keys browsers "$ENV")" -- "$cur") )
                        return 0
                    fi
                    COMPREPLY=( $(compgen -W "--url --env --browser $(_get_keys marks "$ENV")" -- "$cur") )
                elif [[ "$sub_cmd" == "ls" ]]; then
                    COMPREPLY=( $(compgen -W "--env" -- "$cur") )
                elif [[ "$sub_cmd" == "rm" ]]; then
                    if [[ "$cur" == -* ]]; then
                        COMPREPLY=( $(compgen -W "--env" -- "$cur") )
                    else
                        local s_idx=3
                        [[ "$cmd0" == "wd" ]] && s_idx=1
                        _complete_marks $s_idx
                    fi
                fi
                ;;
            protocols)
                if [[ "$target_cword" == 2 ]]; then
                    COMPREPLY=( $(compgen -W "allow deny" -- "$cur") )
                    return 0
                fi
                if [[ "$sub_cmd" == "allow" ]]; then
                    COMPREPLY=( $(compgen -W "--env" -- "$cur") )
                elif [[ "$sub_cmd" == "deny" ]]; then
                    COMPREPLY=( $(compgen -W "--env $(_get_keys protocols "$ENV")" -- "$cur") )
                fi
                ;;
            engines)
                if [[ "$target_cword" == 2 ]]; then
                    COMPREPLY=( $(compgen -W "set ls la rm" -- "$cur") )
                    return 0
                fi
                if [[ "$sub_cmd" == "set" ]]; then
                    COMPREPLY=( $(compgen -W "--url --env $(_get_keys engines "$ENV")" -- "$cur") )
                elif [[ "$sub_cmd" == "ls" ]]; then
                    COMPREPLY=( $(compgen -W "--env --all" -- "$cur") )
                elif [[ "$sub_cmd" == "rm" ]]; then
                    COMPREPLY=( $(compgen -W "--env $(_get_keys engines "$ENV")" -- "$cur") )
                fi
                ;;
            search)
                if [[ "$prev" == "-b" || "$prev" == "--browser" ]]; then
                    COMPREPLY=( $(compgen -W "$(_get_keys browsers "$ENV")" -- "$cur") )
                    return 0
                fi
                if [[ "$prev" == "-s" || "$prev" == "--engine" ]]; then
                    COMPREPLY=( $(compgen -W "$(_get_keys engines "$ENV")" -- "$cur") )
                    return 0
                fi
                COMPREPLY=( $(compgen -W "--engine --browser --env" -- "$cur") )
                ;;
            open|*)
                if [[ "$prev" == "-b" || "$prev" == "--browser" ]]; then
                    COMPREPLY=( $(compgen -W "$(_get_keys browsers "$ENV")" -- "$cur") )
                    return 0
                fi
                if [[ "$cur" == -* ]]; then
                    COMPREPLY=( $(compgen -W "--browser --env" -- "$cur") )
                else
                    local s_idx=2
                    [[ "$cmd0" == "w" ]] && s_idx=1
                    _complete_marks $s_idx
                fi
                ;;
        esac

        if [[ ${#COMPREPLY[@]} -eq 0 ]]; then
            compopt +o default 2>/dev/null || true
        fi
    }

    web.__aliases__() {
        alias w="web open"
        alias wa="web marks set"
        alias wd="web marks rm"
        alias ws="web search"
    }

    web.__init__() {
        __aliases web
        __compl web
        complete -o default -o bashdefault -F web.__compl__ w wa wd ws
    }
}
